-- ================================================================
-- RETAILWIZARD - PHASE 2: GST, ADVANCED ANALYTICS & INTELLIGENCE
-- Database: RWMBSERVER  |  SQL Server
-- Run this AFTER 01_create_views.sql
-- ================================================================

USE [MBGUR03]
GO

-- ================================================================
-- SECTION A: GST & COMPLIANCE VIEWS
-- ================================================================

-- ----------------------------------------------------------------
-- A1. HSN WISE SALES REPORT
-- Purpose: GSTR-1 table 12 - HSN summary of outward supplies
-- ----------------------------------------------------------------
IF OBJECT_ID('dbo.VW_GST_HSN_SALES','V') IS NOT NULL DROP VIEW dbo.VW_GST_HSN_SALES
GO
CREATE VIEW dbo.VW_GST_HSN_SALES AS
SELECT
    D.SD_DEPT_CODE                                          AS DEPT_CODE,
    DATEPART(YEAR,  H.BILL_DATE)                           AS FIN_YEAR,
    DATEPART(MONTH, H.BILL_DATE)                           AS TAX_MONTH,
    DATENAME(MONTH, H.BILL_DATE)                           AS MONTH_NAME,
    ISNULL(D.HSNSACCODE, 'UNCLASSIFIED')                   AS HSN_CODE,
    ISNULL(I.HSN_CODE,d.HSNSACCODE)                       AS ITEM_HSN,
    MAX(I.CONS_UOM)                                        AS UOM,
    COUNT(DISTINCT H.BILL_NO)                              AS BILL_COUNT,
    SUM(ISNULL(D.QTY,0))                                   AS TOTAL_QTY,
    SUM(ISNULL(D.AMOUNT,0) + ISNULL(D.DISC_AMOUNT,0))     AS TAXABLE_VALUE,  -- before disc
    SUM(ISNULL(D.DISC_AMOUNT,0))                           AS TOTAL_DISCOUNT,
    SUM(ISNULL(D.AMOUNT,0))                                AS NET_TAXABLE_VALUE,
    -- GST split (IGST / CGST+SGST based on TAX_TYPE)
    SUM(CASE WHEN ISNULL(D.TAX_TYPE,'') IN ('IGST','I') THEN ISNULL(CAST(D.TAX_AMOUNT AS MONEY),0) ELSE 0 END) AS IGST_AMT,
    SUM(CASE WHEN ISNULL(D.TAX_TYPE,'') NOT IN ('IGST','I') THEN ISNULL(CAST(D.TAX_AMOUNT AS MONEY),0)/2 ELSE 0 END) AS CGST_AMT,
    SUM(CASE WHEN ISNULL(D.TAX_TYPE,'') NOT IN ('IGST','I') THEN ISNULL(CAST(D.TAX_AMOUNT AS MONEY),0)/2 ELSE 0 END) AS SGST_AMT,
    SUM(ISNULL(CAST(D.CESS_AMOUNT AS MONEY),0))           AS CESS_AMT,
    SUM(ISNULL(CAST(D.TAX_AMOUNT AS MONEY),0))            AS TOTAL_TAX,
    SUM(ISNULL(D.AMOUNT,0) + ISNULL(CAST(D.TAX_AMOUNT AS MONEY),0)) AS TOTAL_VALUE,
    MAX(D.TAX_PERCENT)                                     AS GST_RATE
FROM dbo.SALES_HDR H
INNER JOIN dbo.SALES_DTL D ON H.BILL_NO=D.BILL_NO AND H.SH_DEPT_CODE=D.SD_DEPT_CODE
LEFT  JOIN dbo.ITEM_MST I  ON D.SERVICEORPRODUCTCODE=I.ITEM_CODE
WHERE ISNULL(H.ISCANCELLED,0)=0
  AND D.SALES_ITEM_TYPE='P'
GROUP BY D.SD_DEPT_CODE, DATEPART(YEAR,H.BILL_DATE), DATEPART(MONTH,H.BILL_DATE),
         DATENAME(MONTH,H.BILL_DATE),   ISNULL(I.HSN_CODE,d.HSNSACCODE) ,D.HSNSACCODE
GO

-- ----------------------------------------------------------------
-- A2. HSN WISE PURCHASE REPORT
-- Purpose: GSTR-2 / ITC reconciliation, purchase HSN summary
-- ----------------------------------------------------------------
IF OBJECT_ID('dbo.VW_GST_HSN_PURCHASE','V') IS NOT NULL DROP VIEW dbo.VW_GST_HSN_PURCHASE
GO
CREATE VIEW dbo.VW_GST_HSN_PURCHASE AS
SELECT
    H.GH_DEPT_CODE                                          AS DEPT_CODE,
    DATEPART(YEAR,  H.GRN_DATE)                            AS FIN_YEAR,
    DATEPART(MONTH, H.GRN_DATE)                            AS TAX_MONTH,
    DATENAME(MONTH, H.GRN_DATE)                            AS MONTH_NAME,
    ISNULL(D.HSNSACCODE,'UNCLASSIFIED')                    AS HSN_CODE,
    MAX(ISNULL(I.CONS_UOM,'UNT'))                          AS UOM,
    S.SUPPLIER_NAME,
    S.GSTIN_NO                                              AS SUPPLIER_GSTIN,
    COUNT(DISTINCT H.GRN_NO)                               AS GRN_COUNT,
    SUM(ISNULL(D.REC_QTY,0))                              AS TOTAL_QTY,
    SUM(ISNULL(D.AMOUNT,0))                               AS TAXABLE_VALUE,
    SUM(ISNULL(D.TAX_AMOUNT,0))                           AS TOTAL_TAX,
    SUM(CASE WHEN ISNULL(D.TAX_AMOUNT,0)>0
             THEN ISNULL(D.TAX_AMOUNT,0)/2 ELSE 0 END)    AS CGST_AMT,
    SUM(CASE WHEN ISNULL(D.TAX_AMOUNT,0)>0
             THEN ISNULL(D.TAX_AMOUNT,0)/2 ELSE 0 END)    AS SGST_AMT,
    SUM(ISNULL(CAST(D.CESS_AMOUNT AS MONEY),0))           AS CESS_AMT,
    SUM(ISNULL(D.AMOUNT,0) + ISNULL(D.TAX_AMOUNT,0))     AS TOTAL_VALUE,
    MAX(D.TAX_PERCENT)                                     AS GST_RATE,
    CASE WHEN S.GSTIN_NO IS NOT NULL AND LEN(ISNULL(S.GSTIN_NO,''))=15
         THEN 'ELIGIBLE' ELSE 'INELIGIBLE' END             AS ITC_STATUS
FROM dbo.GRN_HDR H
INNER JOIN dbo.GRN_DTL D      ON H.GRN_NO=D.GRN_NO AND H.GH_DEPT_CODE=D.GD_DEPT_CODE
LEFT  JOIN dbo.ITEM_MST I     ON D.ITEM_CODE=I.ITEM_CODE
LEFT  JOIN dbo.SUPPLIER_MST S ON H.SUPPLIERCODE=S.SUPPLIER_CODE
WHERE ISNULL(H.ISCANCELLED,0)=0
GROUP BY H.GH_DEPT_CODE, DATEPART(YEAR,H.GRN_DATE), DATEPART(MONTH,H.GRN_DATE),
         DATENAME(MONTH,H.GRN_DATE), ISNULL(D.HSNSACCODE,'UNCLASSIFIED'),
         S.SUPPLIER_NAME, S.GSTIN_NO
GO

-- ----------------------------------------------------------------
-- A3. GSTR-1 REPORT VIEW
-- B2B: registered buyers | B2C: unregistered | CDNR: credit/debit notes
-- ----------------------------------------------------------------
IF OBJECT_ID('dbo.VW_GST_GSTR1','V') IS NOT NULL DROP VIEW dbo.VW_GST_GSTR1
GO
CREATE VIEW dbo.VW_GST_GSTR1 AS
SELECT
    H.SH_DEPT_CODE                                          AS DEPT_CODE,
    DATEPART(YEAR,  H.BILL_DATE)                           AS FIN_YEAR,
    DATEPART(MONTH, H.BILL_DATE)                           AS TAX_MONTH,
    DATENAME(MONTH, H.BILL_DATE)                           AS MONTH_NAME,
    H.BILL_NO                                               AS BILL_NO,
    CONVERT(DATE, H.BILL_DATE)                             AS BILL_DATE,
    H.GSTBILLNO                                             AS GST_INVOICE_NO,
    H.TRANSACTION_TYPE                                      AS INVOICE_TYPE,
    H.CUSTOMER_CODE,
    H.CUSTOMER                                              AS CUSTOMER_NAME,
    CM.OFFICE1_STATE                                        AS CUSTOMER_STATE,
    -- Invoice category: B2B / B2CS / B2CL / EXP
    CASE
        WHEN H.INVOICE_TPE IN ('EXPORT','EXP')              THEN 'EXP'
        WHEN CM.GSTIN_NO IS NOT NULL AND CM.GSTIN_NO <> '' THEN 'B2B'
        WHEN ISNULL(H.GRAND_TOTAL,0) >= 250000              THEN 'B2CL'
        ELSE 'B2CS'
    END                                                     AS INVOICE_CATEGORY,
    ISNULL(H.SUBTOTAL_AMOUNT,0)                            AS TAXABLE_VALUE,
    -- Tax amounts with expected column names
    SUM(CASE WHEN ISNULL(D.TAX_TYPE,'') IN ('IGST','I')
             THEN ISNULL(CAST(D.TAX_AMOUNT AS MONEY),0) ELSE 0 END) AS IGST_AMT,
    SUM(CASE WHEN ISNULL(D.TAX_TYPE,'') NOT IN ('IGST','I')
             THEN ISNULL(CAST(D.TAX_AMOUNT AS MONEY),0)/2 ELSE 0 END) AS CGST_AMT,
    SUM(CASE WHEN ISNULL(D.TAX_TYPE,'') NOT IN ('IGST','I')
             THEN ISNULL(CAST(D.TAX_AMOUNT AS MONEY),0)/2 ELSE 0 END) AS SGST_AMT,
    SUM(ISNULL(CAST(D.CESS_AMOUNT AS MONEY),0))           AS CESS_AMT,
    SUM(ISNULL(CAST(D.TAX_AMOUNT AS MONEY),0))            AS TOTAL_TAX,
    ISNULL(H.GRAND_TOTAL,0)                               AS INVOICE_VALUE
FROM dbo.SALES_HDR H
INNER JOIN dbo.SALES_DTL D ON H.BILL_NO=D.BILL_NO AND H.SH_DEPT_CODE=D.SD_DEPT_CODE
LEFT  JOIN dbo.CUSTOMER_MST CM ON H.CUSTOMER_CODE=CM.CUSTOMER_CODE
WHERE ISNULL(H.ISCANCELLED,0)=0
GROUP BY H.SH_DEPT_CODE, H.BILL_NO, H.BILL_DATE, H.GSTBILLNO,
         H.CUSTOMER_CODE, H.CUSTOMER, CM.OFFICE1_STATE, CM.CUSTOMER_CODE,
         CM.GSTIN_NO, H.INVOICE_TPE, H.SUBTOTAL_AMOUNT,
         H.GRAND_TOTAL, H.TRANSACTION_TYPE, H.POSID
GO

-- ----------------------------------------------------------------
-- A4. GSTR-3B SUMMARY VIEW
-- Table 3.1: Outward supplies | Table 4: ITC available
-- ----------------------------------------------------------------
IF OBJECT_ID('dbo.VW_GST_GSTR3B','V') IS NOT NULL DROP VIEW dbo.VW_GST_GSTR3B
GO
CREATE VIEW dbo.VW_GST_GSTR3B AS
WITH SALES_TAX AS (
    SELECT
        H.SH_DEPT_CODE AS DEPT_CODE,
        DATEPART(YEAR,  H.BILL_DATE) AS FIN_YEAR,
        DATEPART(MONTH, H.BILL_DATE) AS TAX_MONTH,
        DATENAME(MONTH, H.BILL_DATE) AS MONTH_NAME,
        -- 3.1(a) Taxable outward supplies
        SUM(ISNULL(D.AMOUNT,0))  AS TAXABLE_OUTWARD,
        SUM(CASE WHEN D.TAX_TYPE IN ('IGST','I') THEN ISNULL(CAST(D.TAX_AMOUNT AS MONEY),0) ELSE 0 END) AS IGST_SALES,
        SUM(CASE WHEN D.TAX_TYPE NOT IN ('IGST','I') THEN ISNULL(CAST(D.TAX_AMOUNT AS MONEY),0)/2 ELSE 0 END) AS CGST_SALES,
        SUM(CASE WHEN D.TAX_TYPE NOT IN ('IGST','I') THEN ISNULL(CAST(D.TAX_AMOUNT AS MONEY),0)/2 ELSE 0 END) AS SGST_SALES,
        SUM(ISNULL(CAST(D.CESS_AMOUNT AS MONEY),0)) AS CESS_SALES,
        -- 3.1(c) Nil/exempt
        SUM(CASE WHEN ISNULL(D.TAX_PERCENT,0)=0 THEN ISNULL(D.AMOUNT,0) ELSE 0 END) AS NIL_RATED_SALES
    FROM dbo.SALES_HDR H
    INNER JOIN dbo.SALES_DTL D ON H.BILL_NO=D.BILL_NO AND H.SH_DEPT_CODE=D.SD_DEPT_CODE
    WHERE ISNULL(H.ISCANCELLED,0)=0 AND D.SALES_ITEM_TYPE='P'
    GROUP BY H.SH_DEPT_CODE, DATEPART(YEAR,H.BILL_DATE), DATEPART(MONTH,H.BILL_DATE), DATENAME(MONTH,H.BILL_DATE)
),
PURCHASE_TAX AS (
    SELECT
        H.GH_DEPT_CODE AS DEPT_CODE,
        DATEPART(YEAR,  H.GRN_DATE) AS FIN_YEAR,
        DATEPART(MONTH, H.GRN_DATE) AS TAX_MONTH,
        -- 4: ITC eligible (supplier has valid GSTIN)
        SUM(CASE WHEN S.GSTIN_NO IS NOT NULL AND LEN(ISNULL(S.GSTIN_NO,''))=15
                 THEN ISNULL(D.TAX_AMOUNT,0) ELSE 0 END) AS ITC_ELIGIBLE,
        SUM(CASE WHEN S.GSTIN_NO IS NULL OR LEN(ISNULL(S.GSTIN_NO,''))<>15
                 THEN ISNULL(D.TAX_AMOUNT,0) ELSE 0 END) AS ITC_INELIGIBLE,
        SUM(ISNULL(D.TAX_AMOUNT,0)/2) AS ITC_CGST,
        SUM(ISNULL(D.TAX_AMOUNT,0)/2) AS ITC_SGST
    FROM dbo.GRN_HDR H
    INNER JOIN dbo.GRN_DTL D    ON H.GRN_NO=D.GRN_NO AND H.GH_DEPT_CODE=D.GD_DEPT_CODE
    LEFT  JOIN dbo.SUPPLIER_MST S ON H.SUPPLIERCODE=S.SUPPLIER_CODE
    WHERE ISNULL(H.ISCANCELLED,0)=0
    GROUP BY H.GH_DEPT_CODE, DATEPART(YEAR,H.GRN_DATE), DATEPART(MONTH,H.GRN_DATE)
),
RETURNS_TAX AS (
    SELECT
        RH.SRH_DEPT_CODE AS DEPT_CODE,
        DATEPART(YEAR,  RH.BILL_RTN_DATE) AS FIN_YEAR,
        DATEPART(MONTH, RH.BILL_RTN_DATE) AS TAX_MONTH,
        SUM(ISNULL(RH.GRAND_TOTAL,0)) AS RETURN_VALUE,
        SUM(ISNULL(CAST(RD.TAX_AMOUNT AS MONEY),0)) AS RETURN_TAX
    FROM dbo.SALES_RETURN_HDR RH
    INNER JOIN dbo.SALES_RETURN_DTL RD ON RH.BILL_RTN_NO=RD.BILL_RTN_NO AND RH.SRH_DEPT_CODE=RD.SRD_DEPT_CODE
    GROUP BY RH.SRH_DEPT_CODE, DATEPART(YEAR,RH.BILL_RTN_DATE), DATEPART(MONTH,RH.BILL_RTN_DATE)
)
SELECT
    S.DEPT_CODE, S.FIN_YEAR, S.TAX_MONTH, S.MONTH_NAME,
    -- 3.1 Outward
    S.TAXABLE_OUTWARD,
    S.IGST_SALES, S.CGST_SALES, S.SGST_SALES, S.CESS_SALES,
    S.IGST_SALES+S.CGST_SALES+S.SGST_SALES+S.CESS_SALES AS TOTAL_OUTPUT_TAX,
    S.NIL_RATED_SALES,
    -- Returns (3.1 deduction)
    ISNULL(R.RETURN_VALUE,0)   AS RETURN_VALUE,
    ISNULL(R.RETURN_TAX,0)     AS RETURN_TAX_CREDIT,
    -- 4: ITC
    ISNULL(P.ITC_ELIGIBLE,0)   AS ITC_ELIGIBLE,
    ISNULL(P.ITC_INELIGIBLE,0) AS ITC_INELIGIBLE,
    ISNULL(P.ITC_CGST,0)       AS ITC_CGST,
    ISNULL(P.ITC_SGST,0)       AS ITC_SGST,
    -- Net liability
    (S.IGST_SALES+S.CGST_SALES+S.SGST_SALES+S.CESS_SALES)
    - ISNULL(R.RETURN_TAX,0)
    - ISNULL(P.ITC_ELIGIBLE,0)  AS NET_TAX_LIABILITY
FROM SALES_TAX S
LEFT JOIN PURCHASE_TAX P ON S.DEPT_CODE=P.DEPT_CODE AND S.FIN_YEAR=P.FIN_YEAR AND S.TAX_MONTH=P.TAX_MONTH
LEFT JOIN RETURNS_TAX  R ON S.DEPT_CODE=R.DEPT_CODE AND S.FIN_YEAR=R.FIN_YEAR AND S.TAX_MONTH=R.TAX_MONTH
GO

-- ----------------------------------------------------------------
-- A5. INPUT TAX CREDIT (ITC) DETAIL VIEW
-- ----------------------------------------------------------------
IF OBJECT_ID('dbo.VW_GST_ITC_DETAIL','V') IS NOT NULL DROP VIEW dbo.VW_GST_ITC_DETAIL
GO
CREATE VIEW dbo.VW_GST_ITC_DETAIL AS
SELECT
    H.GH_DEPT_CODE                           AS DEPT_CODE,
    H.GRN_NO,
    CONVERT(DATE, H.GRN_DATE)              AS GRN_DATE,
    DATEPART(YEAR,  H.GRN_DATE)            AS FIN_YEAR,
    DATEPART(MONTH, H.GRN_DATE)            AS TAX_MONTH,
    DATENAME(MONTH, H.GRN_DATE)            AS MONTH_NAME,
    H.INVOICENO                              AS SUPPLIER_INVOICE,
    CONVERT(DATE, H.INVOICE_DATE)          AS INVOICE_DATE,
    S.SUPPLIER_CODE                          AS SUPPLIERCODE,
    S.SUPPLIER_NAME,
    S.GSTIN_NO                               AS SUPPLIER_GSTIN,
    S.PAN_NO                                 AS SUPPLIER_PAN,
    D.ITEM_CODE,
    I.ITEM_NAME,
    ISNULL(D.HSNSACCODE,'')                AS HSN_CODE,
    D.TAX_PERCENT                            AS GST_RATE,
    ISNULL(D.REC_QTY,0)                    AS QTY,
    ISNULL(D.AMOUNT,0)                      AS TAXABLE_VALUE,
    ISNULL(D.TAX_AMOUNT,0)                 AS TOTAL_TAX,
    ISNULL(D.TAX_AMOUNT,0)/2               AS CGST_ITC,
    ISNULL(D.TAX_AMOUNT,0)/2               AS SGST_ITC,
    ISNULL(CAST(D.CESS_AMOUNT AS MONEY),0)  AS CESS_ITC,
    -- ITC eligibility
    CASE WHEN LEN(ISNULL(S.GSTIN_NO,''))=15 THEN 'ELIGIBLE'
         WHEN ISNULL(S.GSTIN_NO,'')=''       THEN 'INELIGIBLE - NO GSTIN'
         ELSE 'INELIGIBLE - INVALID GSTIN'
    END                                      AS ITC_ELIGIBILITY,
    CASE WHEN LEN(ISNULL(S.GSTIN_NO,''))=15
         THEN ISNULL(D.TAX_AMOUNT,0) ELSE 0 END  AS ELIGIBLE_ITC,
    CASE WHEN LEN(ISNULL(S.GSTIN_NO,''))!=15
         THEN ISNULL(D.TAX_AMOUNT,0) ELSE 0 END  AS INELIGIBLE_ITC,
    -- Validation flags
    CASE WHEN H.INVOICE_DATE IS NULL              THEN 'MISSING INVOICE DATE'
         WHEN H.INVOICENO IS NULL OR H.INVOICENO='' THEN 'MISSING INVOICE NO'
         WHEN S.GSTIN_NO IS NULL                  THEN 'SUPPLIER GSTIN MISSING'
         ELSE 'OK' END                            AS VALIDATION_STATUS
FROM dbo.GRN_HDR H
INNER JOIN dbo.GRN_DTL D      ON H.GRN_NO=D.GRN_NO AND H.GH_DEPT_CODE=D.GD_DEPT_CODE
LEFT  JOIN dbo.SUPPLIER_MST S ON H.SUPPLIERCODE=S.SUPPLIER_CODE
LEFT  JOIN dbo.ITEM_MST I     ON D.ITEM_CODE=I.ITEM_CODE
WHERE ISNULL(H.ISCANCELLED,0)=0
GO

-- ----------------------------------------------------------------
-- A6. SALES RETURN (CDNR) VIEW - Credit/Debit Notes for GSTR-1
-- ----------------------------------------------------------------
IF OBJECT_ID('dbo.VW_GST_CDNR','V') IS NOT NULL DROP VIEW dbo.VW_GST_CDNR
GO
CREATE VIEW dbo.VW_GST_CDNR AS
SELECT
    RH.SRH_DEPT_CODE                        AS DEPT_CODE,
    RH.BILL_RTN_NO                          AS NOTE_NO,
    CONVERT(DATE, RH.BILL_RTN_DATE)        AS NOTE_DATE,
    DATEPART(YEAR,  RH.BILL_RTN_DATE)      AS FIN_YEAR,
    DATEPART(MONTH, RH.BILL_RTN_DATE)      AS TAX_MONTH,
    RH.AGAINST_BILL_NO                      AS ORIGINAL_INVOICE,
    'C'                                     AS NOTE_TYPE,  -- C=Credit, D=Debit
    SH.CUSTOMER_CODE,
    SH.CUSTOMER                             AS CUSTOMER_NAME,
    ISNULL(RH.GRAND_TOTAL,0)              AS NOTE_VALUE,
    ISNULL(RH.SUBTOTAL_AMOUNT,0)          AS TAXABLE_VALUE,
    SUM(ISNULL(CAST(RD.TAX_AMOUNT AS MONEY),0)) AS TOTAL_GST,
    SUM(CASE WHEN ISNULL(RD.TAX_TYPE,'') NOT IN ('IGST','I')
             THEN ISNULL(CAST(RD.TAX_AMOUNT AS MONEY),0)/2 ELSE 0 END) AS CGST,
    SUM(CASE WHEN ISNULL(RD.TAX_TYPE,'') NOT IN ('IGST','I')
             THEN ISNULL(CAST(RD.TAX_AMOUNT AS MONEY),0)/2 ELSE 0 END) AS SGST,
    SUM(CASE WHEN ISNULL(RD.TAX_TYPE,'') IN ('IGST','I')
             THEN ISNULL(CAST(RD.TAX_AMOUNT AS MONEY),0) ELSE 0 END) AS IGST,
    RH.REASON_FOR_REFUND
FROM dbo.SALES_RETURN_HDR RH
INNER JOIN dbo.SALES_RETURN_DTL RD ON RH.BILL_RTN_NO=RD.BILL_RTN_NO AND RH.SRH_DEPT_CODE=RD.SRD_DEPT_CODE
LEFT  JOIN dbo.SALES_HDR SH        ON RH.AGAINST_BILL_NO=SH.BILL_NO
GROUP BY RH.SRH_DEPT_CODE, RH.BILL_RTN_NO, RH.BILL_RTN_DATE, RH.AGAINST_BILL_NO,
         SH.CUSTOMER_CODE, SH.CUSTOMER, RH.GRAND_TOTAL, RH.SUBTOTAL_AMOUNT, RH.REASON_FOR_REFUND
GO


-- ================================================================
-- SECTION B: ADVANCED BUSINESS ANALYTICS VIEWS
-- ================================================================

-- ----------------------------------------------------------------
-- B1. CUSTOMER PURCHASE TREND (Monthly/Quarterly/Yearly)
-- ----------------------------------------------------------------
IF OBJECT_ID('dbo.VW_RPT_CUSTOMER_TREND','V') IS NOT NULL DROP VIEW dbo.VW_RPT_CUSTOMER_TREND
GO
CREATE VIEW dbo.VW_RPT_CUSTOMER_TREND AS
SELECT
    H.CUSTOMER_CODE,
    CM.CUSTOMER_NAME,
    CM.OFFICE1_PHONE                        AS MOBILE,
    CM.OFFICE1_EMAIL_ID                     AS EMAIL,
    CM.OFFICE1_CITY                         AS CITY,
    ISNULL(CM.VIP_CUSTOMER,0)             AS IS_VIP,
    H.SH_DEPT_CODE                          AS DEPT_CODE,
    DATEPART(YEAR, H.BILL_DATE)            AS SALE_YEAR,
    DATEPART(MONTH, H.BILL_DATE)           AS SALE_MONTH,
    DATENAME(MONTH, H.BILL_DATE)           AS MONTH_NAME,
    -- Quarter
    CASE DATEPART(MONTH, H.BILL_DATE)
        WHEN 1 THEN 'Q3' WHEN 2 THEN 'Q3' WHEN 3 THEN 'Q3'
        WHEN 4 THEN 'Q4' WHEN 5 THEN 'Q4' WHEN 6 THEN 'Q4'
        WHEN 7 THEN 'Q1' WHEN 8 THEN 'Q1' WHEN 9 THEN 'Q1'
        ELSE 'Q2'
    END                                     AS QUARTER,  -- India FY quarters
    COUNT(H.BILL_NO)                       AS BILL_COUNT,
    SUM(ISNULL(H.GRAND_TOTAL,0))          AS TOTAL_SPENT,
    AVG(ISNULL(H.GRAND_TOTAL,0))          AS AVG_BILL,
    MAX(ISNULL(H.GRAND_TOTAL,0))          AS MAX_BILL,
    SUM(ISNULL(H.DISC_AMOUNT,0))          AS TOTAL_DISCOUNT,
    SUM(ISNULL(H.RedeemAmt,0))            AS POINTS_REDEEMED_VALUE
FROM dbo.SALES_HDR H
INNER JOIN dbo.CUSTOMER_MST CM ON H.CUSTOMER_CODE=CM.CUSTOMER_CODE
WHERE ISNULL(H.ISCANCELLED,0)=0
  AND H.CUSTOMER_CODE IS NOT NULL AND H.CUSTOMER_CODE > 0
GROUP BY H.CUSTOMER_CODE, CM.CUSTOMER_NAME, CM.OFFICE1_PHONE, CM.OFFICE1_EMAIL_ID,
         CM.OFFICE1_CITY, CM.VIP_CUSTOMER, H.SH_DEPT_CODE,
         DATEPART(YEAR,H.BILL_DATE), DATEPART(MONTH,H.BILL_DATE), DATENAME(MONTH,H.BILL_DATE)
GO

-- ----------------------------------------------------------------
-- B2. CUSTOMER SEGMENTATION & INTELLIGENCE VIEW
-- RFM: Recency, Frequency, Monetary scoring
-- ----------------------------------------------------------------
IF OBJECT_ID('dbo.VW_RPT_CUSTOMER_SEGMENTS','V') IS NOT NULL DROP VIEW dbo.VW_RPT_CUSTOMER_SEGMENTS
GO
CREATE VIEW dbo.VW_RPT_CUSTOMER_SEGMENTS AS
WITH BASE AS (
    SELECT
        H.CUSTOMER_CODE,
        CM.CUSTOMER_NAME,
        CM.OFFICE1_PHONE                        AS MOBILE,
        CM.OFFICE1_EMAIL_ID                     AS EMAIL,
        CM.OFFICE1_CITY                         AS CITY,
        CM.OFFICE1_STATE                        AS STATE,
        ISNULL(CM.VIP_CUSTOMER,0)             AS IS_VIP,
        CM.DATEOFBIRTH,
        CM.CARD_TYPE,
        ISNULL(CM.BALANCE_POINTS,0)           AS LOYALTY_POINTS,
        CONVERT(DATE, CM.Last_Visit)           AS LAST_VISIT,
        CONVERT(DATE, CM.First_Visit)          AS FIRST_VISIT,
        DATEDIFF(DAY, CM.Last_Visit, GETDATE()) AS DAYS_INACTIVE,
        COUNT(H.BILL_NO)                       AS TOTAL_VISITS,
        SUM(ISNULL(H.GRAND_TOTAL,0))          AS LIFETIME_VALUE,
        AVG(ISNULL(H.GRAND_TOTAL,0))          AS AVG_BILL_VALUE,
        MAX(ISNULL(H.GRAND_TOTAL,0))          AS MAX_BILL,
        MIN(CONVERT(DATE, H.BILL_DATE))        AS FIRST_PURCHASE,
        MAX(CONVERT(DATE, H.BILL_DATE))        AS LAST_PURCHASE
    FROM dbo.CUSTOMER_MST CM
    LEFT JOIN dbo.SALES_HDR H ON CM.CUSTOMER_CODE=H.CUSTOMER_CODE AND ISNULL(H.ISCANCELLED,0)=0
    GROUP BY H.CUSTOMER_CODE, CM.CUSTOMER_NAME, CM.OFFICE1_PHONE, CM.OFFICE1_EMAIL_ID,
             CM.OFFICE1_CITY, CM.OFFICE1_STATE, CM.VIP_CUSTOMER, CM.DATEOFBIRTH,
             CM.CARD_TYPE, CM.BALANCE_POINTS, CM.Last_Visit, CM.First_Visit
)
SELECT *,
    -- RFM Scores (1-5 scale)
    CASE WHEN DAYS_INACTIVE <= 30  THEN 5
         WHEN DAYS_INACTIVE <= 60  THEN 4
         WHEN DAYS_INACTIVE <= 90  THEN 3
         WHEN DAYS_INACTIVE <= 180 THEN 2 ELSE 1 END          AS R_SCORE,
    CASE WHEN TOTAL_VISITS >= 24 THEN 5
         WHEN TOTAL_VISITS >= 12 THEN 4
         WHEN TOTAL_VISITS >= 6  THEN 3
         WHEN TOTAL_VISITS >= 2  THEN 2 ELSE 1 END             AS F_SCORE,
    CASE WHEN LIFETIME_VALUE >= 100000 THEN 5
         WHEN LIFETIME_VALUE >= 50000  THEN 4
         WHEN LIFETIME_VALUE >= 20000  THEN 3
         WHEN LIFETIME_VALUE >= 5000   THEN 2 ELSE 1 END       AS M_SCORE,
    -- Segment
    CASE
        WHEN DAYS_INACTIVE <= 30  AND TOTAL_VISITS >= 6  AND LIFETIME_VALUE >= 20000 THEN 'CHAMPION'
        WHEN DAYS_INACTIVE <= 60  AND TOTAL_VISITS >= 4  AND LIFETIME_VALUE >= 10000 THEN 'LOYAL'
        WHEN DAYS_INACTIVE <= 30  AND TOTAL_VISITS <= 2                              THEN 'NEW CUSTOMER'
        WHEN DAYS_INACTIVE BETWEEN 61 AND 120 AND TOTAL_VISITS >= 4                 THEN 'AT RISK'
        WHEN DAYS_INACTIVE > 120 AND TOTAL_VISITS >= 3                              THEN 'LOST'
        WHEN DAYS_INACTIVE > 180                                                     THEN 'INACTIVE'
        WHEN LIFETIME_VALUE >= 50000                                                 THEN 'HIGH VALUE'
        ELSE 'REGULAR'
    END                                                          AS CUSTOMER_SEGMENT,
    -- Promotion suggestion
    CASE
        WHEN DAYS_INACTIVE > 180                                         THEN 'WE MISS YOU - 15% OFF'
        WHEN DAYS_INACTIVE BETWEEN 91 AND 180                           THEN 'COME BACK OFFER - 10% OFF'
        WHEN LIFETIME_VALUE >= 50000 AND DAYS_INACTIVE <= 30            THEN 'VIP REWARD - SPECIAL GIFT'
        WHEN TOTAL_VISITS >= 12                                          THEN 'LOYALTY BONUS - EXTRA POINTS'
        WHEN TOTAL_VISITS = 1                                            THEN 'WELCOME BACK - 5% NEXT VISIT'
        ELSE 'STANDARD OFFER'
    END                                                          AS PROMO_SUGGESTION,
    -- Birthday flag
    CASE WHEN DATEOFBIRTH IS NOT NULL
              AND MONTH(DATEOFBIRTH)=MONTH(GETDATE())
              AND DAY(DATEOFBIRTH) BETWEEN DAY(GETDATE()) AND DAY(GETDATE())+7
         THEN 1 ELSE 0 END                                     AS BIRTHDAY_THIS_WEEK
FROM BASE
GO

-- ----------------------------------------------------------------
-- B3. ITEM / PRODUCT TREND ANALYSIS
-- ----------------------------------------------------------------
IF OBJECT_ID('dbo.VW_RPT_ITEM_TREND','V') IS NOT NULL DROP VIEW dbo.VW_RPT_ITEM_TREND
GO
CREATE VIEW dbo.VW_RPT_ITEM_TREND AS
SELECT
    D.SERVICEORPRODUCTCODE                  AS ITEM_CODE,
    I.ITEM_NAME,
    I.EAN_CODE,
    CAT.Category_Desc                       AS CATEGORY,
    BRD.Brand_Name                          AS BRAND,
    D.SD_DEPT_CODE                          AS DEPT_CODE,
    DATEPART(YEAR,  H.BILL_DATE)           AS SALE_YEAR,
    DATEPART(MONTH, H.BILL_DATE)           AS SALE_MONTH,
    DATENAME(MONTH, H.BILL_DATE)           AS MONTH_NAME,
    COUNT(DISTINCT H.BILL_NO)              AS BILL_COUNT,
    COUNT(DISTINCT H.CUSTOMER_CODE)        AS UNIQUE_CUSTOMERS,
    SUM(ISNULL(D.QTY,0))                  AS QTY_SOLD,
    SUM(ISNULL(D.AMOUNT,0))               AS SALES_VALUE,
    SUM(ISNULL(D.DISC_AMOUNT,0))          AS DISCOUNT_GIVEN,
    AVG(ISNULL(D.RATE,0))                 AS AVG_SELLING_RATE,
    SUM(ISNULL(D.AMOUNT,0) - ISNULL(D.ORG_CP,0)*ISNULL(D.QTY,0)) AS GROSS_PROFIT,
    CASE WHEN SUM(ISNULL(D.AMOUNT,0))>0
         THEN SUM(ISNULL(D.AMOUNT,0) - ISNULL(D.ORG_CP,0)*ISNULL(D.QTY,0))
              / SUM(ISNULL(D.AMOUNT,0)) * 100
         ELSE 0 END                         AS MARGIN_PCT,
    -- Stock status
    ISNULL(I.QOH,0)                        AS CURRENT_STOCK,
    ISNULL(I.REORDER_LVL,0)              AS REORDER_LEVEL
FROM dbo.SALES_HDR H
INNER JOIN dbo.SALES_DTL D  ON H.BILL_NO=D.BILL_NO AND H.SH_DEPT_CODE=D.SD_DEPT_CODE
LEFT  JOIN dbo.ITEM_MST I   ON D.SERVICEORPRODUCTCODE=I.ITEM_CODE
LEFT  JOIN dbo.Category_Mst CAT ON I.CATEGORY_CODE=CAT.Category_Code
LEFT  JOIN dbo.Brand_Master BRD ON I.BRAND_CODE=BRD.Brand_Code
WHERE ISNULL(H.ISCANCELLED,0)=0 AND D.SALES_ITEM_TYPE='P'
GROUP BY D.SERVICEORPRODUCTCODE, I.ITEM_NAME, I.EAN_CODE, CAT.Category_Desc,
         BRD.Brand_Name, D.SD_DEPT_CODE, DATEPART(YEAR,H.BILL_DATE),
         DATEPART(MONTH,H.BILL_DATE), DATENAME(MONTH,H.BILL_DATE), I.QOH, I.REORDER_LVL
GO

-- ----------------------------------------------------------------
-- B4. FAST/SLOW MOVING ITEMS
-- ----------------------------------------------------------------
IF OBJECT_ID('dbo.VW_RPT_ITEM_VELOCITY','V') IS NOT NULL DROP VIEW dbo.VW_RPT_ITEM_VELOCITY
GO
CREATE VIEW dbo.VW_RPT_ITEM_VELOCITY AS
WITH ITEM_SALES AS (
    SELECT
        D.SERVICEORPRODUCTCODE AS ITEM_CODE,
        SUM(ISNULL(D.QTY,0)) AS QTY_SOLD_90D,
        COUNT(DISTINCT H.BILL_NO) AS BILL_COUNT_90D,
        SUM(ISNULL(D.AMOUNT,0)) AS SALES_VALUE_90D,
        MAX(CONVERT(DATE,H.BILL_DATE)) AS LAST_SOLD_DATE,
        DATEDIFF(DAY, MAX(H.BILL_DATE), GETDATE()) AS DAYS_SINCE_SOLD
    FROM dbo.SALES_HDR H
    INNER JOIN dbo.SALES_DTL D ON H.BILL_NO=D.BILL_NO AND H.SH_DEPT_CODE=D.SD_DEPT_CODE
    WHERE ISNULL(H.ISCANCELLED,0)=0
      AND H.BILL_DATE >= DATEADD(DAY,-90,GETDATE())
      AND D.SALES_ITEM_TYPE='P'
    GROUP BY D.SERVICEORPRODUCTCODE
)
SELECT
    I.ITEM_CODE, I.ITEM_NAME, I.EAN_CODE,
    CAT.Category_Desc AS CATEGORY, BRD.Brand_Name AS BRAND,
    S.SUPPLIER_NAME,
    ISNULL(I.QOH,0)               AS STOCK_QTY,
    ISNULL(I.CP,0)                AS COST_PRICE,
    ISNULL(I.MRP,0)               AS MRP,
    ISNULL(I.QOH,0)*ISNULL(I.CP,0) AS STOCK_VALUE,
    ISNULL(IS2.QTY_SOLD_90D,0)   AS QTY_SOLD_90D,
    ISNULL(IS2.BILL_COUNT_90D,0) AS BILLS_90D,
    ISNULL(IS2.SALES_VALUE_90D,0) AS SALES_VALUE_90D,
    IS2.LAST_SOLD_DATE,
    ISNULL(IS2.DAYS_SINCE_SOLD,999) AS DAYS_SINCE_LAST_SOLD,
    -- Velocity classification
    CASE
        WHEN ISNULL(IS2.QTY_SOLD_90D,0) = 0 THEN 'NON-MOVING'
        WHEN ISNULL(IS2.QTY_SOLD_90D,0)/90.0 >= 3 THEN 'FAST MOVING'
        WHEN ISNULL(IS2.QTY_SOLD_90D,0)/90.0 >= 1 THEN 'MEDIUM MOVING'
        WHEN ISNULL(IS2.QTY_SOLD_90D,0)/90.0 >= 0.1 THEN 'SLOW MOVING'
        ELSE 'VERY SLOW'
    END AS VELOCITY,
    -- Days of stock remaining
    CASE WHEN ISNULL(IS2.QTY_SOLD_90D,0)>0
         THEN ISNULL(I.QOH,0) / (ISNULL(IS2.QTY_SOLD_90D,0)/90.0)
         ELSE 9999 END AS DAYS_STOCK_REMAINING
FROM dbo.ITEM_MST I
LEFT JOIN ITEM_SALES IS2 ON I.ITEM_CODE=IS2.ITEM_CODE
LEFT JOIN dbo.Category_Mst CAT ON I.CATEGORY_CODE=CAT.Category_Code
LEFT JOIN dbo.Brand_Master BRD ON I.BRAND_CODE=BRD.Brand_Code
LEFT JOIN dbo.SUPPLIER_MST S   ON I.SUPPLIER_CODE=S.SUPPLIER_CODE
WHERE ISNULL(I.Discontinue,0)=0
GO

-- ----------------------------------------------------------------
-- B5. PROFITABILITY REPORT (Item-wise & Customer-wise)
-- ----------------------------------------------------------------
IF OBJECT_ID('dbo.VW_RPT_PROFITABILITY','V') IS NOT NULL DROP VIEW dbo.VW_RPT_PROFITABILITY
GO
CREATE VIEW dbo.VW_RPT_PROFITABILITY AS
SELECT
    D.SD_DEPT_CODE                              AS DEPT_CODE,
    DATEPART(YEAR,  H.BILL_DATE)               AS SALE_YEAR,
    DATEPART(MONTH, H.BILL_DATE)               AS SALE_MONTH,
    DATENAME(MONTH, H.BILL_DATE)               AS MONTH_NAME,
    D.SERVICEORPRODUCTCODE                      AS ITEM_CODE,
    I.ITEM_NAME,
    CAT.Category_Desc                           AS CATEGORY,
    H.CUSTOMER_CODE,
    H.CUSTOMER                                  AS CUSTOMER_NAME,
    SUM(ISNULL(D.QTY,0))                       AS QTY_SOLD,
    SUM(ISNULL(D.AMOUNT,0))                    AS REVENUE,
    SUM(ISNULL(D.ORG_CP,0)*ISNULL(D.QTY,0))  AS COGS,
    SUM(ISNULL(D.DISC_AMOUNT,0))              AS DISCOUNT,
    SUM(ISNULL(CAST(D.TAX_AMOUNT AS MONEY),0)) AS TAX_COLLECTED,
    SUM(ISNULL(D.AMOUNT,0) - ISNULL(D.ORG_CP,0)*ISNULL(D.QTY,0)) AS GROSS_PROFIT,
    CASE WHEN SUM(ISNULL(D.AMOUNT,0))>0
         THEN SUM(ISNULL(D.AMOUNT,0)-ISNULL(D.ORG_CP,0)*ISNULL(D.QTY,0))
              /SUM(ISNULL(D.AMOUNT,0))*100
         ELSE 0 END                             AS GROSS_MARGIN_PCT,
    -- MRP vs SP gap = pricing efficiency
    SUM(ISNULL(D.ITM_MRP,0)*ISNULL(D.QTY,0)) AS MRP_VALUE,
    SUM(ISNULL(D.ITM_MRP,0)*ISNULL(D.QTY,0)) - SUM(ISNULL(D.AMOUNT,0)) AS MRP_DISC_GIVEN
FROM dbo.SALES_HDR H
INNER JOIN dbo.SALES_DTL D  ON H.BILL_NO=D.BILL_NO AND H.SH_DEPT_CODE=D.SD_DEPT_CODE
LEFT  JOIN dbo.ITEM_MST I   ON D.SERVICEORPRODUCTCODE=I.ITEM_CODE
LEFT  JOIN dbo.Category_Mst CAT ON I.CATEGORY_CODE=CAT.Category_Code
WHERE ISNULL(H.ISCANCELLED,0)=0 AND D.SALES_ITEM_TYPE='P'
GROUP BY D.SD_DEPT_CODE, DATEPART(YEAR,H.BILL_DATE), DATEPART(MONTH,H.BILL_DATE),
         DATENAME(MONTH,H.BILL_DATE), D.SERVICEORPRODUCTCODE, I.ITEM_NAME,
         CAT.Category_Desc, H.CUSTOMER_CODE, H.CUSTOMER
GO

-- ----------------------------------------------------------------
-- B6. SALES vs PURCHASE COMPARISON
-- ----------------------------------------------------------------
IF OBJECT_ID('dbo.VW_RPT_SALES_VS_PURCHASE','V') IS NOT NULL DROP VIEW dbo.VW_RPT_SALES_VS_PURCHASE
GO
CREATE VIEW dbo.VW_RPT_SALES_VS_PURCHASE AS
WITH SAL AS (
    SELECT SH_DEPT_CODE AS DEPT_CODE,
           DATEPART(YEAR,BILL_DATE) AS YR, DATEPART(MONTH,BILL_DATE) AS MO,
           DATENAME(MONTH,BILL_DATE) AS MONTH_NAME,
           SUM(ISNULL(GRAND_TOTAL,0)) AS SALES_VALUE,
           COUNT(BILL_NO) AS SALES_BILLS
    FROM dbo.SALES_HDR WHERE ISNULL(ISCANCELLED,0)=0
    GROUP BY SH_DEPT_CODE, DATEPART(YEAR,BILL_DATE), DATEPART(MONTH,BILL_DATE), DATENAME(MONTH,BILL_DATE)
),
PUR AS (
    SELECT GH_DEPT_CODE AS DEPT_CODE,
           DATEPART(YEAR,GRN_DATE) AS YR, DATEPART(MONTH,GRN_DATE) AS MO,
           SUM(ISNULL(GRANDTOTAL,0)) AS PURCHASE_VALUE,
           COUNT(GRN_NO) AS PURCHASE_GRNS
    FROM dbo.GRN_HDR WHERE ISNULL(ISCANCELLED,0)=0
    GROUP BY GH_DEPT_CODE, DATEPART(YEAR,GRN_DATE), DATEPART(MONTH,GRN_DATE)
),
RTN AS (
    SELECT SRH_DEPT_CODE AS DEPT_CODE,
           DATEPART(YEAR,BILL_RTN_DATE) AS YR, DATEPART(MONTH,BILL_RTN_DATE) AS MO,
           SUM(ISNULL(GRAND_TOTAL,0)) AS RETURN_VALUE
    FROM dbo.SALES_RETURN_HDR
    GROUP BY SRH_DEPT_CODE, DATEPART(YEAR,BILL_RTN_DATE), DATEPART(MONTH,BILL_RTN_DATE)
)
SELECT S.DEPT_CODE, S.YR AS YEAR, S.MO AS MONTH, S.MONTH_NAME,
       ISNULL(S.SALES_VALUE,0)     AS SALES_VALUE,
       ISNULL(S.SALES_BILLS,0)     AS SALES_BILLS,
       ISNULL(P.PURCHASE_VALUE,0)  AS PURCHASE_VALUE,
       ISNULL(P.PURCHASE_GRNS,0)   AS PURCHASE_GRNS,
       ISNULL(R.RETURN_VALUE,0)    AS RETURN_VALUE,
       ISNULL(S.SALES_VALUE,0) - ISNULL(P.PURCHASE_VALUE,0) AS NET_MARGIN,
       ISNULL(S.SALES_VALUE,0) - ISNULL(R.RETURN_VALUE,0)   AS NET_SALES,
       CASE WHEN ISNULL(P.PURCHASE_VALUE,0)>0
            THEN (ISNULL(S.SALES_VALUE,0)-ISNULL(P.PURCHASE_VALUE,0))/ISNULL(P.PURCHASE_VALUE,0)*100
            ELSE 0 END AS GROSS_MARGIN_PCT
FROM SAL S
LEFT JOIN PUR P ON S.DEPT_CODE=P.DEPT_CODE AND S.YR=P.YR AND S.MO=P.MO
LEFT JOIN RTN R ON S.DEPT_CODE=R.DEPT_CODE AND S.YR=R.YR AND S.MO=R.MO
GO

-- ----------------------------------------------------------------
-- B7. DAILY BUSINESS DASHBOARD VIEW
-- ----------------------------------------------------------------
IF OBJECT_ID('dbo.VW_RPT_DASHBOARD','V') IS NOT NULL DROP VIEW dbo.VW_RPT_DASHBOARD
GO
CREATE VIEW dbo.VW_RPT_DASHBOARD AS
WITH TODAY_SALES AS (
    SELECT SH_DEPT_CODE AS DEPT_CODE,
           COUNT(BILL_NO) AS TODAY_BILLS,
           SUM(ISNULL(GRAND_TOTAL,0)) AS TODAY_SALES,
           SUM(ISNULL(DISC_AMOUNT,0)) AS TODAY_DISCOUNT,
           AVG(ISNULL(GRAND_TOTAL,0)) AS TODAY_AVG_BILL,
           SUM(ISNULL(RedeemAmt,0)) AS TODAY_REDEEMED
    FROM dbo.SALES_HDR
    WHERE CONVERT(DATE,BILL_DATE)=CONVERT(DATE,GETDATE()) AND ISNULL(ISCANCELLED,0)=0
    GROUP BY SH_DEPT_CODE
),
YESTERDAY_SALES AS (
    SELECT SH_DEPT_CODE AS DEPT_CODE,
           COUNT(BILL_NO) AS YEST_BILLS,
           SUM(ISNULL(GRAND_TOTAL,0)) AS YEST_SALES
    FROM dbo.SALES_HDR
    WHERE CONVERT(DATE,BILL_DATE)=CONVERT(DATE,DATEADD(DAY,-1,GETDATE())) AND ISNULL(ISCANCELLED,0)=0
    GROUP BY SH_DEPT_CODE
),
MTD AS (
    SELECT SH_DEPT_CODE AS DEPT_CODE,
           SUM(ISNULL(GRAND_TOTAL,0)) AS MTD_SALES,
           COUNT(BILL_NO) AS MTD_BILLS
    FROM dbo.SALES_HDR
    WHERE MONTH(BILL_DATE)=MONTH(GETDATE()) AND YEAR(BILL_DATE)=YEAR(GETDATE()) AND ISNULL(ISCANCELLED,0)=0
    GROUP BY SH_DEPT_CODE
),
STOCK_ALERTS AS (
    SELECT COUNT(*) AS LOW_STOCK_ITEMS
    FROM dbo.ITEM_MST
    WHERE ISNULL(QOH,0) <= ISNULL(REORDER_LVL,0) AND ISNULL(Discontinue,0)=0
)
SELECT
    T.DEPT_CODE,
    ISNULL(T.TODAY_BILLS,0)     AS TODAY_BILLS,
    ISNULL(T.TODAY_SALES,0)     AS TODAY_SALES,
    ISNULL(T.TODAY_DISCOUNT,0)  AS TODAY_DISCOUNT,
    ISNULL(T.TODAY_AVG_BILL,0)  AS TODAY_AVG_BILL,
    ISNULL(T.TODAY_REDEEMED,0)  AS TODAY_REDEEMED,
    ISNULL(Y.YEST_BILLS,0)      AS YEST_BILLS,
    ISNULL(Y.YEST_SALES,0)      AS YEST_SALES,
    ISNULL(M.MTD_SALES,0)       AS MTD_SALES,
    ISNULL(M.MTD_BILLS,0)       AS MTD_BILLS,
    -- Growth vs yesterday
    CASE WHEN ISNULL(Y.YEST_SALES,0)>0
         THEN (ISNULL(T.TODAY_SALES,0)-ISNULL(Y.YEST_SALES,0))/ISNULL(Y.YEST_SALES,0)*100
         ELSE 0 END              AS DOD_GROWTH_PCT,
    SA.LOW_STOCK_ITEMS,
    GETDATE()                    AS DASHBOARD_TIME
FROM TODAY_SALES T
LEFT JOIN YESTERDAY_SALES Y ON T.DEPT_CODE=Y.DEPT_CODE
LEFT JOIN MTD M ON T.DEPT_CODE=M.DEPT_CODE
CROSS JOIN STOCK_ALERTS SA
GO

-- ----------------------------------------------------------------
-- B8. STOCK VALUATION REPORT
-- ----------------------------------------------------------------
IF OBJECT_ID('dbo.VW_RPT_STOCK_VALUATION','V') IS NOT NULL DROP VIEW dbo.VW_RPT_STOCK_VALUATION
GO
CREATE VIEW dbo.VW_RPT_STOCK_VALUATION AS
SELECT
    I.ITEM_CODE, I.ITEM_NAME, I.EAN_CODE,
    CAT.Category_Desc AS CATEGORY, BRD.Brand_Name AS BRAND,
    S.SUPPLIER_NAME,
    I.PUR_UOM AS UOM,
    ISNULL(I.QOH,0) AS QTY_ON_HAND,
    ISNULL(I.BASIC_COST,0) AS BASIC_COST,
    ISNULL(I.CP,0) AS COST_PRICE,
    ISNULL(I.MRP,0) AS MRP,
    ISNULL(I.SP,0) AS SALE_PRICE,
    -- Valuation methods
    ISNULL(I.QOH,0) * ISNULL(I.BASIC_COST,0) AS VALUE_AT_BASIC_COST,
    ISNULL(I.QOH,0) * ISNULL(I.CP,0)         AS VALUE_AT_COST_PRICE,
    ISNULL(I.QOH,0) * ISNULL(I.MRP,0)        AS VALUE_AT_MRP,
    ISNULL(I.QOH,0) * ISNULL(I.SP,0)         AS VALUE_AT_SP,
    -- Potential profit
    ISNULL(I.QOH,0) * (ISNULL(I.SP,0)-ISNULL(I.CP,0)) AS POTENTIAL_PROFIT,
    CASE WHEN ISNULL(I.SP,0)>0
         THEN (ISNULL(I.SP,0)-ISNULL(I.CP,0))/ISNULL(I.SP,0)*100
         ELSE 0 END AS MARGIN_PCT,
    -- Alerts
    CASE WHEN ISNULL(I.QOH,0) <= 0 THEN 'OUT OF STOCK'
         WHEN ISNULL(I.QOH,0) <= ISNULL(I.REORDER_LVL,0) THEN 'REORDER'
         ELSE 'OK' END AS STOCK_STATUS,
    I.EXP_DATE AS EXPIRY_DATE,
    ISNULL(I.SHElFLIFE,0) AS SHELF_LIFE_DAYS
FROM dbo.ITEM_MST I
LEFT JOIN dbo.Category_Mst CAT ON I.CATEGORY_CODE=CAT.Category_Code
LEFT JOIN dbo.Brand_Master BRD ON I.BRAND_CODE=BRD.Brand_Code
LEFT JOIN dbo.SUPPLIER_MST S   ON I.SUPPLIER_CODE=S.SUPPLIER_CODE
WHERE ISNULL(I.Discontinue,0)=0
GO

-- ----------------------------------------------------------------
-- B9. EXCEPTION REPORT - Abnormal transactions, anomalies
-- ----------------------------------------------------------------
IF OBJECT_ID('dbo.VW_RPT_EXCEPTIONS','V') IS NOT NULL DROP VIEW dbo.VW_RPT_EXCEPTIONS
GO
CREATE VIEW dbo.VW_RPT_EXCEPTIONS AS
-- Abnormally high bills (> 3x average)
SELECT 'HIGH BILL AMOUNT' AS EXCEPTION_TYPE,
       H.SH_DEPT_CODE AS DEPT_CODE,
       CAST(H.BILL_NO AS VARCHAR) AS REFERENCE_NO,
       CONVERT(DATE,H.BILL_DATE) AS TXN_DATE,
       H.CUSTOMER AS CUSTOMER_NAME,
       'Bill amount ' + CAST(ISNULL(H.GRAND_TOTAL,0) AS VARCHAR) + ' is unusually high' AS EXCEPTION_DETAIL,
       ISNULL(H.GRAND_TOTAL,0) AS AMOUNT,
       'HIGH' AS SEVERITY
FROM dbo.SALES_HDR H
WHERE ISNULL(H.ISCANCELLED,0)=0
  AND ISNULL(H.GRAND_TOTAL,0) > (SELECT AVG(ISNULL(GRAND_TOTAL,0))*3 FROM dbo.SALES_HDR WHERE ISNULL(ISCANCELLED,0)=0)

UNION ALL

-- Negative stock items
SELECT 'NEGATIVE STOCK' AS EXCEPTION_TYPE,
       '' AS DEPT_CODE,
       CAST(ITEM_CODE AS VARCHAR) AS REFERENCE_NO,
       GETDATE() AS TXN_DATE,
       ITEM_NAME AS CUSTOMER_NAME,
       'Negative QOH: ' + CAST(ISNULL(QOH,0) AS VARCHAR) AS EXCEPTION_DETAIL,
       ISNULL(QOH,0)*ISNULL(CP,0) AS AMOUNT,
       'CRITICAL' AS SEVERITY
FROM dbo.ITEM_MST WHERE ISNULL(QOH,0) < 0 AND ISNULL(Discontinue,0)=0

UNION ALL

-- Zero-cost items sold (CP=0 but sold)
SELECT 'ZERO COST ITEM SOLD' AS EXCEPTION_TYPE,
       D.SD_DEPT_CODE AS DEPT_CODE,
       CAST(D.BILL_NO AS VARCHAR) AS REFERENCE_NO,
       CONVERT(DATE,H.BILL_DATE) AS TXN_DATE,
       I.ITEM_NAME AS CUSTOMER_NAME,
       'Item sold with zero cost price - profit % may be wrong' AS EXCEPTION_DETAIL,
       ISNULL(D.AMOUNT,0) AS AMOUNT,
       'MEDIUM' AS SEVERITY
FROM dbo.SALES_DTL D
INNER JOIN dbo.SALES_HDR H ON D.BILL_NO=H.BILL_NO AND D.SD_DEPT_CODE=H.SH_DEPT_CODE
LEFT  JOIN dbo.ITEM_MST I ON D.SERVICEORPRODUCTCODE=I.ITEM_CODE
WHERE ISNULL(D.ORG_CP,0)=0 AND ISNULL(D.AMOUNT,0)>0
  AND ISNULL(H.ISCANCELLED,0)=0 AND H.BILL_DATE >= DATEADD(DAY,-30,GETDATE())

UNION ALL

-- High discount bills (>30%)
SELECT 'EXCESSIVE DISCOUNT' AS EXCEPTION_TYPE,
       H.SH_DEPT_CODE AS DEPT_CODE,
       CAST(H.BILL_NO AS VARCHAR) AS REFERENCE_NO,
       CONVERT(DATE,H.BILL_DATE) AS TXN_DATE,
       H.CUSTOMER AS CUSTOMER_NAME,
       'Discount ' + CAST(CAST(ISNULL(H.DISC_PER,0) AS DECIMAL(5,1)) AS VARCHAR) + '% exceeds threshold' AS EXCEPTION_DETAIL,
       ISNULL(H.DISC_AMOUNT,0) AS AMOUNT,
       'MEDIUM' AS SEVERITY
FROM dbo.SALES_HDR H
WHERE ISNULL(H.ISCANCELLED,0)=0
  AND ISNULL(H.DISC_PER,0) > 30
  AND H.BILL_DATE >= DATEADD(DAY,-30,GETDATE())
GO

-- ================================================================
-- SECTION C: PERFORMANCE INDEXES
-- ================================================================
-- Run these once to dramatically speed up all reports

-- Sales HDR indexes
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name='IX_SALES_HDR_DATE_DEPT' AND object_id=OBJECT_ID('SALES_HDR'))
    CREATE NONCLUSTERED INDEX IX_SALES_HDR_DATE_DEPT ON dbo.SALES_HDR(BILL_DATE, SH_DEPT_CODE) INCLUDE (BILL_NO, CUSTOMER_CODE, GRAND_TOTAL, DISC_AMOUNT, ISCANCELLED)
GO
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name='IX_SALES_HDR_CUST' AND object_id=OBJECT_ID('SALES_HDR'))
    CREATE NONCLUSTERED INDEX IX_SALES_HDR_CUST ON dbo.SALES_HDR(CUSTOMER_CODE) INCLUDE (BILL_DATE, GRAND_TOTAL, SH_DEPT_CODE)
GO

-- Sales DTL indexes
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name='IX_SALES_DTL_BILL_DEPT' AND object_id=OBJECT_ID('SALES_DTL'))
    CREATE NONCLUSTERED INDEX IX_SALES_DTL_BILL_DEPT ON dbo.SALES_DTL(BILL_NO, SD_DEPT_CODE) INCLUDE (SERVICEORPRODUCTCODE, QTY, RATE, AMOUNT, TAX_AMOUNT, DISC_AMOUNT, ORG_CP, HSNSACCODE, TAX_TYPE)
GO
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name='IX_SALES_DTL_ITEM' AND object_id=OBJECT_ID('SALES_DTL'))
    CREATE NONCLUSTERED INDEX IX_SALES_DTL_ITEM ON dbo.SALES_DTL(SERVICEORPRODUCTCODE) INCLUDE (BILL_NO, QTY, AMOUNT, SD_DEPT_CODE)
GO

-- GRN indexes
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name='IX_GRN_HDR_DATE' AND object_id=OBJECT_ID('GRN_HDR'))
    CREATE NONCLUSTERED INDEX IX_GRN_HDR_DATE ON dbo.GRN_HDR(GRN_DATE, GH_DEPT_CODE) INCLUDE (GRN_NO, SUPPLIERCODE, GRANDTOTAL)
GO

-- Customer index
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name='IX_CUSTOMER_MST_LASTVISIT' AND object_id=OBJECT_ID('CUSTOMER_MST'))
    CREATE NONCLUSTERED INDEX IX_CUSTOMER_MST_LASTVISIT ON dbo.CUSTOMER_MST(Last_Visit) INCLUDE (CUSTOMER_CODE, CUSTOMER_NAME, OFFICE1_PHONE, OFFICE1_EMAIL_ID)
GO

-- Item MST index
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name='IX_ITEM_MST_CAT_BRAND' AND object_id=OBJECT_ID('ITEM_MST'))
    CREATE NONCLUSTERED INDEX IX_ITEM_MST_CAT_BRAND ON dbo.ITEM_MST(CATEGORY_CODE, BRAND_CODE) INCLUDE (ITEM_CODE, ITEM_NAME, QOH, CP, MRP, SP, REORDER_LVL)
GO

PRINT '================================================================'
PRINT 'Phase 2 Views & Indexes Created Successfully!'
PRINT 'Views: GST_HSN_SALES, GST_HSN_PURCHASE, GST_GSTR1, GST_GSTR3B'
PRINT '       GST_ITC_DETAIL, GST_CDNR'
PRINT '       RPT_CUSTOMER_TREND, RPT_CUSTOMER_SEGMENTS'
PRINT '       RPT_ITEM_TREND, RPT_ITEM_VELOCITY, RPT_PROFITABILITY'
PRINT '       RPT_SALES_VS_PURCHASE, RPT_DASHBOARD'
PRINT '       RPT_STOCK_VALUATION, RPT_EXCEPTIONS'
PRINT 'Indexes: 7 performance indexes created'
PRINT '================================================================'
GO
