-- ================================================================
-- RETAILWIZARD FMCG - COMPLETE SQL VIEWS SCRIPT
-- Run this ENTIRE file in SSMS on database: RWMBSERVER
-- Safe to run multiple times (DROP + CREATE pattern)
-- ================================================================

USE [RWMBSERVER]
GO

PRINT '== PHASE 1: CORE REPORT VIEWS =='
GO

-- ────────────────────────────────────────────────────────────────
-- 1. SALES SUMMARY
-- ────────────────────────────────────────────────────────────────
IF OBJECT_ID('dbo.VW_RPT_SALES_SUMMARY','V') IS NOT NULL DROP VIEW dbo.VW_RPT_SALES_SUMMARY
GO
CREATE VIEW dbo.VW_RPT_SALES_SUMMARY AS
SELECT
    H.SH_DEPT_CODE                      AS DEPT_CODE,
    H.BILL_NO,
    CONVERT(DATE, H.BILL_DATE)          AS BILL_DATE,
    DATEPART(YEAR,  H.BILL_DATE)        AS BILL_YEAR,
    DATEPART(MONTH, H.BILL_DATE)        AS BILL_MONTH,
    DATENAME(WEEKDAY, H.BILL_DATE)      AS DAY_NAME,
    H.CUSTOMER_CODE,
    H.CUSTOMER                          AS CUSTOMER_NAME,
    ISNULL(H.SUBTOTAL_AMOUNT, 0)        AS SUBTOTAL,
    ISNULL(H.DISC_AMOUNT, 0)            AS DISCOUNT,
    ISNULL(H.GRAND_TOTAL, 0)            AS GRAND_TOTAL,
    ISNULL(H.TENDERED_AMOUNT, 0)        AS TENDERED,
    ISNULL(H.RedeemAmt, 0)             AS REDEEM_AMOUNT,
    ISNULL(H.RoundOffBillAmount, 0)     AS ROUND_OFF,
    ISNULL(H.ISCANCELLED, 0)            AS IS_CANCELLED,
    H.ENT_USERID                        AS CASHIER_ID,
    H.POSID                             AS POS_ID,
    H.Shift_ID,
    H.TRANSACTION_TYPE
FROM dbo.SALES_HDR H
WHERE ISNULL(H.ISCANCELLED, 0) = 0
GO

-- ────────────────────────────────────────────────────────────────
-- 2. SALES DETAIL (item-wise)
-- ────────────────────────────────────────────────────────────────
IF OBJECT_ID('dbo.VW_RPT_SALES_DETAIL','V') IS NOT NULL DROP VIEW dbo.VW_RPT_SALES_DETAIL
GO
CREATE VIEW dbo.VW_RPT_SALES_DETAIL AS
SELECT
    H.SH_DEPT_CODE                      AS DEPT_CODE,
    H.BILL_NO,
    CONVERT(DATE, H.BILL_DATE)          AS BILL_DATE,
    DATEPART(YEAR,  H.BILL_DATE)        AS BILL_YEAR,
    DATEPART(MONTH, H.BILL_DATE)        AS BILL_MONTH,
    H.CUSTOMER_CODE,
    H.CUSTOMER                          AS CUSTOMER_NAME,
    D.SERVICEORPRODUCTCODE              AS ITEM_CODE,
    I.ITEM_NAME,
    CAT.Category_Desc                   AS CATEGORY,
    BRD.Brand_Name                      AS BRAND,
    ISNULL(D.QTY, 0)                    AS QTY,
    ISNULL(D.RATE, 0)                   AS RATE,
    ISNULL(D.ITM_MRP, 0)               AS MRP,
    ISNULL(D.ORG_CP, 0)                AS COST_PRICE,
    ISNULL(D.AMOUNT, 0)                AS AMOUNT,
    ISNULL(D.DISC_AMOUNT, 0)           AS DISC_AMOUNT,
    ISNULL(D.Line_Disc_Amount, 0)      AS LINE_DISC,
    ISNULL(D.TOTAL, 0)                 AS TOTAL,
    ISNULL(D.AMOUNT,0) - ISNULL(D.ORG_CP,0)*ISNULL(D.QTY,0)  AS GROSS_PROFIT,
    CASE WHEN ISNULL(D.AMOUNT,0)>0
         THEN ((ISNULL(D.AMOUNT,0)-ISNULL(D.ORG_CP,0)*ISNULL(D.QTY,0))/ISNULL(D.AMOUNT,0))*100
         ELSE 0 END                     AS MARGIN_PCT,
    D.HSNSACCODE                        AS HSN_CODE,
    ISNULL(D.TAX_PERCENT, 0)           AS TAX_PERCENT,
    ISNULL(D.TAX_AMOUNT, 0)            AS TAX_AMOUNT
FROM dbo.SALES_HDR H
INNER JOIN dbo.SALES_DTL D   ON H.BILL_NO=D.BILL_NO AND H.SH_DEPT_CODE=D.SD_DEPT_CODE
LEFT  JOIN dbo.ITEM_MST I    ON D.SERVICEORPRODUCTCODE=I.ITEM_CODE
LEFT  JOIN dbo.Category_Mst CAT ON I.CATEGORY_CODE=CAT.Category_Code
LEFT  JOIN dbo.Brand_Master BRD ON I.BRAND_CODE=BRD.Brand_Code
WHERE ISNULL(H.ISCANCELLED,0)=0 AND D.SALES_ITEM_TYPE='P'
GO

-- ────────────────────────────────────────────────────────────────
-- 3. PAYMENT COLLECTION
-- ────────────────────────────────────────────────────────────────
IF OBJECT_ID('dbo.VW_RPT_PAYMENT_COLLECTION','V') IS NOT NULL DROP VIEW dbo.VW_RPT_PAYMENT_COLLECTION
GO
CREATE VIEW dbo.VW_RPT_PAYMENT_COLLECTION AS
SELECT
    H.SH_DEPT_CODE                      AS DEPT_CODE,
    H.BILL_NO,
    CONVERT(DATE, H.BILL_DATE)          AS BILL_DATE,
    DATEPART(YEAR,  H.BILL_DATE)        AS BILL_YEAR,
    DATEPART(MONTH, H.BILL_DATE)        AS BILL_MONTH,
    P.PAY_CODE,
    PM.PayMode                          AS PAYMENT_MODE,
    ISNULL(P.PAY_AMOUNT, 0)            AS PAY_AMOUNT,
    H.GRAND_TOTAL
FROM dbo.SALES_HDR H
INNER JOIN dbo.SALES_PAYMENT_DTL P ON H.BILL_NO=P.BILL_NO AND H.SH_DEPT_CODE=P.SPD_DEPT_CODE
LEFT  JOIN dbo.Payment_Mode PM      ON P.PAY_CODE=PM.PayCode
WHERE ISNULL(H.ISCANCELLED,0)=0
GO

-- ────────────────────────────────────────────────────────────────
-- 4. SALES RETURN
-- ────────────────────────────────────────────────────────────────
IF OBJECT_ID('dbo.VW_RPT_SALES_RETURN','V') IS NOT NULL DROP VIEW dbo.VW_RPT_SALES_RETURN
GO
CREATE VIEW dbo.VW_RPT_SALES_RETURN AS
SELECT
    RH.SRH_DEPT_CODE                    AS DEPT_CODE,
    RH.BILL_RTN_NO,
    CONVERT(DATE, RH.BILL_RTN_DATE)     AS RETURN_DATE,
    DATEPART(YEAR,  RH.BILL_RTN_DATE)   AS RTN_YEAR,
    DATEPART(MONTH, RH.BILL_RTN_DATE)   AS RTN_MONTH,
    RH.AGAINST_BILL_NO,
    RD.SERVICEORPRODUCTCODE             AS ITEM_CODE,
    I.ITEM_NAME,
    CAT.Category_Desc                   AS CATEGORY,
    ISNULL(RD.QTY, 0)                  AS RTN_QTY,
    ISNULL(RD.RATE, 0)                 AS RATE,
    ISNULL(RD.AMOUNT, 0)              AS AMOUNT,
    ISNULL(RH.GRAND_TOTAL, 0)         AS GRAND_TOTAL,
    RH.REASON_FOR_REFUND,
    PM.PayMode                          AS REFUND_MODE,
    ISNULL(RP.PAY_AMOUNT, 0)          AS REFUND_AMOUNT
FROM dbo.SALES_RETURN_HDR RH
INNER JOIN dbo.SALES_RETURN_DTL RD  ON RH.BILL_RTN_NO=RD.BILL_RTN_NO AND RH.SRH_DEPT_CODE=RD.SRD_DEPT_CODE
LEFT  JOIN dbo.ITEM_MST I           ON RD.SERVICEORPRODUCTCODE=I.ITEM_CODE
LEFT  JOIN dbo.Category_Mst CAT    ON I.CATEGORY_CODE=CAT.Category_Code
LEFT  JOIN dbo.SALES_RTN_PAYMENT_DTL RP ON RH.BILL_RTN_NO=RP.BILL_RTN_NO AND RH.SRH_DEPT_CODE=RP.SRPD_DEPT_CODE
LEFT  JOIN dbo.Payment_Mode PM      ON RP.PAY_CODE=PM.PayCode
GO

-- ────────────────────────────────────────────────────────────────
-- 5. CUSTOMER MASTER
-- ────────────────────────────────────────────────────────────────
IF OBJECT_ID('dbo.VW_RPT_CUSTOMER','V') IS NOT NULL DROP VIEW dbo.VW_RPT_CUSTOMER
GO
CREATE VIEW dbo.VW_RPT_CUSTOMER AS
SELECT
    C.CUSTOMER_CODE,
    C.CUSTOMER_NAME,
    C.GENDER,
    CONVERT(DATE, C.DATEOFBIRTH)        AS DATE_OF_BIRTH,
    ISNULL(C.VIP_CUSTOMER, 0)          AS IS_VIP,
    C.CARD_TYPE,
    C.CARD_NUMBER,
    CONVERT(DATE, C.CARD_ISSUE_DATE)    AS CARD_ISSUE_DATE,
    CONVERT(DATE, C.CARD_EXPIRY_DATE)   AS CARD_EXPIRY_DATE,
    ISNULL(C.NO_OF_TRANSACTIONS, 0)    AS TOTAL_TRANSACTIONS,
    ISNULL(C.TRANSACTION_VALUE, 0)     AS TOTAL_VALUE,
    ISNULL(C.TOTAL_POINTS, 0)         AS TOTAL_POINTS,
    ISNULL(C.POINTS_REDEEM, 0)        AS POINTS_REDEEMED,
    ISNULL(C.BALANCE_POINTS, 0)       AS BALANCE_POINTS,
    C.OFFICE1_PHONE                    AS MOBILE,
    C.OFFICE1_EMAIL_ID                 AS EMAIL,
    C.OFFICE1_ADDRESS1                 AS ADDRESS,
    C.OFFICE1_CITY                     AS CITY,
    C.OFFICE1_STATE                    AS STATE,
    CONVERT(DATE, C.First_Visit)       AS FIRST_VISIT,
    CONVERT(DATE, C.Last_Visit)        AS LAST_VISIT,
    ISNULL(C.No_of_Visits, 0)         AS NO_OF_VISITS,
    ISNULL(C.Avg_Bill_Amount, 0)      AS AVG_BILL_AMOUNT,
    ISNULL(C.IsCredit_Customer, 0)    AS IS_CREDIT_CUSTOMER,
    ISNULL(C.Credit_Limit, 0)        AS CREDIT_LIMIT,
    ISNULL(C.Credit_Transactions_Value,0) AS CREDIT_USED,
    ISNULL(C.Credit_Payment_Received,0)   AS CREDIT_PAID
FROM dbo.CUSTOMER_MST C
GO

-- ────────────────────────────────────────────────────────────────
-- 6. CUSTOMER LEDGER
-- ────────────────────────────────────────────────────────────────
IF OBJECT_ID('dbo.VW_RPT_CUSTOMER_LEDGER','V') IS NOT NULL DROP VIEW dbo.VW_RPT_CUSTOMER_LEDGER
GO
CREATE VIEW dbo.VW_RPT_CUSTOMER_LEDGER AS
SELECT
    H.CUSTOMER_CODE,
    CM.CUSTOMER_NAME,
    CM.OFFICE1_PHONE                    AS MOBILE,
    H.SH_DEPT_CODE                      AS DEPT_CODE,
    H.BILL_NO,
    CONVERT(DATE, H.BILL_DATE)         AS BILL_DATE,
    ISNULL(H.GRAND_TOTAL, 0)          AS BILL_AMOUNT,
    ISNULL(H.DISC_AMOUNT, 0)          AS DISCOUNT,
    ISNULL(H.RedeemAmt, 0)            AS REDEEM_AMOUNT,
    PM.PayMode                          AS PAYMENT_MODE,
    ISNULL(P.PAY_AMOUNT, 0)          AS PAID_AMOUNT,
    ISNULL(H.BALANCE_AMOUNT, 0)      AS BALANCE
FROM dbo.SALES_HDR H
INNER JOIN dbo.CUSTOMER_MST CM ON H.CUSTOMER_CODE=CM.CUSTOMER_CODE
LEFT  JOIN dbo.SALES_PAYMENT_DTL P ON H.BILL_NO=P.BILL_NO AND H.SH_DEPT_CODE=P.SPD_DEPT_CODE
LEFT  JOIN dbo.Payment_Mode PM ON P.PAY_CODE=PM.PayCode
WHERE ISNULL(H.ISCANCELLED,0)=0
  AND H.CUSTOMER_CODE IS NOT NULL AND H.CUSTOMER_CODE>0
GO

-- ────────────────────────────────────────────────────────────────
-- 7. LOYALTY LEDGER
-- ────────────────────────────────────────────────────────────────
IF OBJECT_ID('dbo.VW_RPT_LOYALTY_LEDGER','V') IS NOT NULL DROP VIEW dbo.VW_RPT_LOYALTY_LEDGER
GO
CREATE VIEW dbo.VW_RPT_LOYALTY_LEDGER AS
SELECT
    LP.CUSTOMER_CODE,
    CM.CUSTOMER_NAME,
    CM.OFFICE1_PHONE                   AS MOBILE,
    LP.TRANSACTION_NO,
    CONVERT(DATE, LP.TRANSACTION_DATE) AS TXN_DATE,
    LP.TRANSACTION_TYPE                AS TXN_TYPE,
    ISNULL(LP.POINTSCOLLECTED, 0)     AS POINTS_EARNED,
    ISNULL(LP.COLLECTEDVALUE, 0)      AS EARN_VALUE,
    ISNULL(LP.POINTSDEDUCTED, 0)     AS POINTS_REDEEMED,
    ISNULL(LP.DEDUCTEDVALUE, 0)      AS REDEEM_VALUE,
    ISNULL(LP.BillValue, 0)          AS BILL_VALUE,
    ISNULL(LP.SinglePointValue, 0)   AS POINT_VALUE,
    LP.CLP_DEPT_CODE                  AS DEPT_CODE
FROM dbo.CUST_LOYALTY_POINTS LP
LEFT JOIN dbo.CUSTOMER_MST CM ON LP.CUSTOMER_CODE=CM.CUSTOMER_CODE
GO

-- ────────────────────────────────────────────────────────────────
-- 8. PURCHASE SUMMARY (GRN)
-- ────────────────────────────────────────────────────────────────
IF OBJECT_ID('dbo.VW_RPT_PURCHASE_SUMMARY','V') IS NOT NULL DROP VIEW dbo.VW_RPT_PURCHASE_SUMMARY
GO
CREATE VIEW dbo.VW_RPT_PURCHASE_SUMMARY AS
SELECT
    H.GH_DEPT_CODE                      AS DEPT_CODE,
    H.GRN_NO,
    CONVERT(DATE, H.GRN_DATE)          AS GRN_DATE,
    DATEPART(YEAR,  H.GRN_DATE)        AS GRN_YEAR,
    DATEPART(MONTH, H.GRN_DATE)        AS GRN_MONTH,
    H.INVOICENO                         AS SUPPLIER_INVOICE_NO,
    CONVERT(DATE, H.INVOICE_DATE)      AS INVOICE_DATE,
    H.SUPPLIERCODE,
    S.SUPPLIER_NAME,
    S.OFFICE1_PHONE                    AS SUPPLIER_PHONE,
    ISNULL(H.SUBTOTAL, 0)             AS SUBTOTAL,
    ISNULL(H.TOTALLINEDISCAMOUNT, 0) AS TOTAL_DISCOUNT,
    ISNULL(H.TOTALTAXAMOUNT, 0)      AS TOTAL_TAX,
    ISNULL(H.GRANDTOTAL, 0)         AS GRAND_TOTAL,
    ISNULL(H.TOTALQTY, 0)           AS TOTAL_QTY,
    ISNULL(H.FRIEGHT, 0)            AS FREIGHT,
    ISNULL(H.OTHERCHARGES, 0)       AS OTHER_CHARGES,
    ISNULL(H.ISCANCELLED, 0)        AS IS_CANCELLED,
    H.REMARKS,
    H.AUTH_STATUS,
    H.PO_NO
FROM dbo.GRN_HDR H
LEFT JOIN dbo.SUPPLIER_MST S ON H.SUPPLIERCODE=S.SUPPLIER_CODE
WHERE ISNULL(H.ISCANCELLED,0)=0
GO

-- ────────────────────────────────────────────────────────────────
-- 9. PURCHASE DETAIL
-- ────────────────────────────────────────────────────────────────
IF OBJECT_ID('dbo.VW_RPT_PURCHASE_DETAIL','V') IS NOT NULL DROP VIEW dbo.VW_RPT_PURCHASE_DETAIL
GO
CREATE VIEW dbo.VW_RPT_PURCHASE_DETAIL AS
SELECT
    H.GH_DEPT_CODE                      AS DEPT_CODE,
    H.GRN_NO,
    CONVERT(DATE, H.GRN_DATE)          AS GRN_DATE,
    DATEPART(YEAR,  H.GRN_DATE)        AS GRN_YEAR,
    DATEPART(MONTH, H.GRN_DATE)        AS GRN_MONTH,
    H.SUPPLIERCODE,
    S.SUPPLIER_NAME,
    D.ITEM_CODE,
    I.ITEM_NAME,
    CAT.Category_Desc                  AS CATEGORY,
    BRD.Brand_Name                     AS BRAND,
    ISNULL(D.REC_QTY, 0)             AS RECEIVED_QTY,
    ISNULL(D.FREE_QTY, 0)            AS FREE_QTY,
    ISNULL(D.BASIC_COST, 0)          AS BASIC_COST,
    ISNULL(D.CP, 0)                  AS COST_PRICE,
    ISNULL(D.SP, 0)                  AS SALE_PRICE,
    ISNULL(D.MRP, 0)                 AS MRP,
    ISNULL(D.AMOUNT, 0)             AS AMOUNT,
    ISNULL(D.ITEM_DISC_AMOUNT, 0)   AS ITEM_DISC,
    ISNULL(D.BILL_DISC_AMOUNT, 0)   AS BILL_DISC,
    ISNULL(D.TAX_AMOUNT, 0)         AS TAX_AMOUNT,
    D.HSNSACCODE                      AS HSN_CODE,
    D.EANCODE                         AS EAN_CODE
FROM dbo.GRN_HDR H
INNER JOIN dbo.GRN_DTL D    ON H.GRN_NO=D.GRN_NO AND H.GH_DEPT_CODE=D.GD_DEPT_CODE
LEFT  JOIN dbo.SUPPLIER_MST S   ON H.SUPPLIERCODE=S.SUPPLIER_CODE
LEFT  JOIN dbo.ITEM_MST I       ON D.ITEM_CODE=I.ITEM_CODE
LEFT  JOIN dbo.Category_Mst CAT ON I.CATEGORY_CODE=CAT.Category_Code
LEFT  JOIN dbo.Brand_Master BRD ON I.BRAND_CODE=BRD.Brand_Code
WHERE ISNULL(H.ISCANCELLED,0)=0
GO

-- ────────────────────────────────────────────────────────────────
-- 10. PURCHASE RETURN
-- ────────────────────────────────────────────────────────────────
IF OBJECT_ID('dbo.VW_RPT_PURCHASE_RETURN','V') IS NOT NULL DROP VIEW dbo.VW_RPT_PURCHASE_RETURN
GO
CREATE VIEW dbo.VW_RPT_PURCHASE_RETURN AS
SELECT
    H.PH_DEPT_CODE                      AS DEPT_CODE,
    H.PRN_NO,
    CONVERT(DATE, H.PRN_DATE)          AS PRN_DATE,
    H.SUPPLIERCODE,
    S.SUPPLIER_NAME,
    D.ITEM_CODE,
    I.ITEM_NAME,
    CAT.Category_Desc                  AS CATEGORY,
    ISNULL(D.RTN_QTY, 0)             AS RETURN_QTY,
    ISNULL(D.CP, 0)                  AS COST_PRICE,
    ISNULL(D.MRP, 0)                 AS MRP,
    ISNULL(D.AMOUNT, 0)             AS AMOUNT,
    ISNULL(D.TAX_AMOUNT, 0)         AS TAX_AMOUNT,
    ISNULL(H.GRANDTOTAL, 0)        AS GRAND_TOTAL,
    H.REMARKS,
    D.GRN_NO                          AS AGAINST_GRN
FROM dbo.PRN_HDR H
INNER JOIN dbo.PRN_DTL D     ON H.PRN_NO=D.PRN_NO AND H.PH_DEPT_CODE=D.PD_DEPT_CODE
LEFT  JOIN dbo.SUPPLIER_MST S   ON H.SUPPLIERCODE=S.SUPPLIER_CODE
LEFT  JOIN dbo.ITEM_MST I       ON D.ITEM_CODE=I.ITEM_CODE
LEFT  JOIN dbo.Category_Mst CAT ON I.CATEGORY_CODE=CAT.Category_Code
GO

-- ────────────────────────────────────────────────────────────────
-- 11. STOCK TRANSFER (MTN)
-- ────────────────────────────────────────────────────────────────
IF OBJECT_ID('dbo.VW_RPT_STOCK_TRANSFER','V') IS NOT NULL DROP VIEW dbo.VW_RPT_STOCK_TRANSFER
GO
CREATE VIEW dbo.VW_RPT_STOCK_TRANSFER AS
SELECT
    H.MH_DEPT_CODE                      AS DEPT_CODE,
    H.MTN_NO,
    CONVERT(DATE, H.MTN_DATE)          AS TRANSFER_DATE,
    H.MTN_TYPE,
    CASE H.MTN_TYPE WHEN 'O' THEN 'Transfer Out'
                    WHEN 'I' THEN 'Transfer In'
                    ELSE H.MTN_TYPE END AS TRANSFER_TYPE,
    H.FROM_LOCATION,
    H.TO_LOCATION,
    D.ITEM_CODE,
    I.ITEM_NAME,
    CAT.Category_Desc                  AS CATEGORY,
    BRD.Brand_Name                     AS BRAND,
    ISNULL(D.QTY, 0)                  AS QTY,
    ISNULL(D.CP, 0)                   AS COST_PRICE,
    ISNULL(D.SP, 0)                   AS SALE_PRICE,
    ISNULL(D.MRP, 0)                  AS MRP,
    ISNULL(D.AMOUNT, 0)              AS AMOUNT,
    H.VEHICLE_NO,
    H.REMARKS,
    H.AUTH_STATUS
FROM dbo.MTN_HDR H
INNER JOIN dbo.MTN_DTL D     ON H.MTN_NO=D.MTN_NO AND H.MH_DEPT_CODE=D.MD_DEPT_CODE
LEFT  JOIN dbo.ITEM_MST I       ON D.ITEM_CODE=I.ITEM_CODE
LEFT  JOIN dbo.Category_Mst CAT ON I.CATEGORY_CODE=CAT.Category_Code
LEFT  JOIN dbo.Brand_Master BRD ON I.BRAND_CODE=BRD.Brand_Code
GO

-- ────────────────────────────────────────────────────────────────
-- 12. STOCK STATUS
-- ────────────────────────────────────────────────────────────────
IF OBJECT_ID('dbo.VW_RPT_STOCK_STATUS','V') IS NOT NULL DROP VIEW dbo.VW_RPT_STOCK_STATUS
GO
CREATE VIEW dbo.VW_RPT_STOCK_STATUS AS
SELECT
    I.ITEM_CODE,
    I.ITEM_NAME,
    I.EAN_CODE,
    CAT.Category_Desc                  AS CATEGORY,
    BRD.Brand_Name                     AS BRAND,
    S.SUPPLIER_NAME,
    ISNULL(I.QOH, 0)                  AS QTY_ON_HAND,
    ISNULL(I.REORDER_LVL, 0)         AS REORDER_LEVEL,
    ISNULL(I.MIN_STOCK_LVL, 0)      AS MIN_STOCK,
    ISNULL(I.MAX_STOCK_LVL, 0)      AS MAX_STOCK,
    ISNULL(I.CP, 0)                   AS COST_PRICE,
    ISNULL(I.MRP, 0)                  AS MRP,
    ISNULL(I.SP, 0)                   AS SALE_PRICE,
    ISNULL(I.WSP, 0)                  AS WHOLESALE_PRICE,
    ISNULL(I.QOH,0)*ISNULL(I.CP,0)   AS STOCK_VALUE_CP,
    ISNULL(I.QOH,0)*ISNULL(I.MRP,0)  AS STOCK_VALUE_MRP,
    I.HSN_CODE,
    I.PUR_UOM                          AS PURCHASE_UOM,
    I.CONS_UOM                         AS SALE_UOM,
    ISNULL(I.Discontinue,0)           AS IS_DISCONTINUED,
    CASE
        WHEN ISNULL(I.QOH,0)<=0 THEN 'OUT OF STOCK'
        WHEN ISNULL(I.QOH,0)<=ISNULL(I.REORDER_LVL,0) THEN 'REORDER REQUIRED'
        WHEN ISNULL(I.QOH,0)<=ISNULL(I.MIN_STOCK_LVL,0) THEN 'LOW STOCK'
        ELSE 'NORMAL'
    END AS STOCK_STATUS,
    I.EXP_DATE                         AS EXPIRY_DATE,
    CASE
        WHEN I.EXP_DATE IS NOT NULL AND I.EXP_DATE<GETDATE() THEN 'EXPIRED'
        WHEN I.EXP_DATE IS NOT NULL AND I.EXP_DATE<DATEADD(DAY,30,GETDATE()) THEN 'EXPIRING SOON'
        ELSE 'OK'
    END AS EXPIRY_STATUS
FROM dbo.ITEM_MST I
LEFT JOIN dbo.Category_Mst CAT  ON I.CATEGORY_CODE=CAT.Category_Code
LEFT JOIN dbo.Brand_Master BRD  ON I.BRAND_CODE=BRD.Brand_Code
LEFT JOIN dbo.SUPPLIER_MST S    ON I.SUPPLIER_CODE=S.SUPPLIER_CODE
WHERE ISNULL(I.Discontinue,0)=0
GO

-- ────────────────────────────────────────────────────────────────
-- 13. DAILY TREND  ← THIS WAS CAUSING THE ERROR
-- ────────────────────────────────────────────────────────────────
IF OBJECT_ID('dbo.VW_RPT_DAILY_TREND','V') IS NOT NULL DROP VIEW dbo.VW_RPT_DAILY_TREND
GO
CREATE VIEW dbo.VW_RPT_DAILY_TREND AS
SELECT
    SH_DEPT_CODE                              AS DEPT_CODE,
    CONVERT(DATE, BILL_DATE)                  AS SALE_DATE,
    DATEPART(YEAR,  BILL_DATE)               AS YEAR,
    DATEPART(MONTH, BILL_DATE)               AS MONTH,
    DATENAME(MONTH, BILL_DATE)               AS MONTH_NAME,
    DATEPART(DAY,   BILL_DATE)               AS DAY,
    DATENAME(WEEKDAY, BILL_DATE)             AS WEEKDAY,
    COUNT(BILL_NO)                            AS BILL_COUNT,
    SUM(ISNULL(GRAND_TOTAL,0))               AS TOTAL_SALES,
    SUM(ISNULL(DISC_AMOUNT,0))               AS TOTAL_DISCOUNT,
    SUM(ISNULL(SUBTOTAL_AMOUNT,0))           AS SUBTOTAL,
    AVG(ISNULL(GRAND_TOTAL,0))               AS AVG_BILL_VALUE,
    MAX(ISNULL(GRAND_TOTAL,0))               AS MAX_BILL_VALUE,
    MIN(ISNULL(GRAND_TOTAL,0))               AS MIN_BILL_VALUE,
    SUM(ISNULL(RedeemAmt,0))                AS TOTAL_REDEEMED
FROM dbo.SALES_HDR
WHERE ISNULL(ISCANCELLED,0)=0
GROUP BY SH_DEPT_CODE, CONVERT(DATE,BILL_DATE),
         DATEPART(YEAR,BILL_DATE),DATEPART(MONTH,BILL_DATE),
         DATENAME(MONTH,BILL_DATE),DATEPART(DAY,BILL_DATE),
         DATENAME(WEEKDAY,BILL_DATE)
GO

-- ────────────────────────────────────────────────────────────────
-- 14. TOP ITEMS
-- ────────────────────────────────────────────────────────────────
IF OBJECT_ID('dbo.VW_RPT_TOP_ITEMS','V') IS NOT NULL DROP VIEW dbo.VW_RPT_TOP_ITEMS
GO
CREATE VIEW dbo.VW_RPT_TOP_ITEMS AS
SELECT
    D.SD_DEPT_CODE                      AS DEPT_CODE,
    D.SERVICEORPRODUCTCODE              AS ITEM_CODE,
    I.ITEM_NAME,
    CAT.Category_Desc                  AS CATEGORY,
    BRD.Brand_Name                     AS BRAND,
    COUNT(DISTINCT D.BILL_NO)          AS BILL_COUNT,
    SUM(ISNULL(D.QTY,0))              AS TOTAL_QTY_SOLD,
    SUM(ISNULL(D.AMOUNT,0))           AS TOTAL_SALES,
    SUM(ISNULL(D.DISC_AMOUNT,0))      AS TOTAL_DISCOUNT,
    AVG(ISNULL(D.RATE,0))             AS AVG_RATE,
    SUM(ISNULL(D.AMOUNT,0)-ISNULL(D.ORG_CP,0)*ISNULL(D.QTY,0)) AS GROSS_PROFIT
FROM dbo.SALES_DTL D
INNER JOIN dbo.SALES_HDR H      ON D.BILL_NO=H.BILL_NO AND D.SD_DEPT_CODE=H.SH_DEPT_CODE
LEFT  JOIN dbo.ITEM_MST I       ON D.SERVICEORPRODUCTCODE=I.ITEM_CODE
LEFT  JOIN dbo.Category_Mst CAT ON I.CATEGORY_CODE=CAT.Category_Code
LEFT  JOIN dbo.Brand_Master BRD ON I.BRAND_CODE=BRD.Brand_Code
WHERE ISNULL(H.ISCANCELLED,0)=0 AND D.SALES_ITEM_TYPE='P'
GROUP BY D.SD_DEPT_CODE,D.SERVICEORPRODUCTCODE,I.ITEM_NAME,CAT.Category_Desc,BRD.Brand_Name
GO

-- ────────────────────────────────────────────────────────────────
-- 15. CATEGORY SALES
-- ────────────────────────────────────────────────────────────────
IF OBJECT_ID('dbo.VW_RPT_CATEGORY_SALES','V') IS NOT NULL DROP VIEW dbo.VW_RPT_CATEGORY_SALES
GO
CREATE VIEW dbo.VW_RPT_CATEGORY_SALES AS
SELECT
    D.SD_DEPT_CODE                      AS DEPT_CODE,
    DATEPART(YEAR,  H.BILL_DATE)       AS YEAR,
    DATEPART(MONTH, H.BILL_DATE)       AS MONTH,
    DATENAME(MONTH, H.BILL_DATE)       AS MONTH_NAME,
    CAT.Category_Code,
    CAT.Category_Desc                  AS CATEGORY,
    COUNT(DISTINCT H.BILL_NO)          AS BILL_COUNT,
    SUM(ISNULL(D.QTY,0))              AS TOTAL_QTY,
    SUM(ISNULL(D.AMOUNT,0))           AS TOTAL_SALES,
    SUM(ISNULL(D.DISC_AMOUNT,0))      AS TOTAL_DISCOUNT,
    SUM(ISNULL(D.AMOUNT,0)-ISNULL(D.ORG_CP,0)*ISNULL(D.QTY,0)) AS GROSS_PROFIT
FROM dbo.SALES_DTL D
INNER JOIN dbo.SALES_HDR H      ON D.BILL_NO=H.BILL_NO AND D.SD_DEPT_CODE=H.SH_DEPT_CODE
LEFT  JOIN dbo.ITEM_MST I       ON D.SERVICEORPRODUCTCODE=I.ITEM_CODE
LEFT  JOIN dbo.Category_Mst CAT ON I.CATEGORY_CODE=CAT.Category_Code
WHERE ISNULL(H.ISCANCELLED,0)=0 AND D.SALES_ITEM_TYPE='P'
GROUP BY D.SD_DEPT_CODE,DATEPART(YEAR,H.BILL_DATE),DATEPART(MONTH,H.BILL_DATE),
         DATENAME(MONTH,H.BILL_DATE),CAT.Category_Code,CAT.Category_Desc
GO

-- ────────────────────────────────────────────────────────────────
-- 16. SUPPLIER PERFORMANCE
-- ────────────────────────────────────────────────────────────────
IF OBJECT_ID('dbo.VW_RPT_SUPPLIER_PERFORMANCE','V') IS NOT NULL DROP VIEW dbo.VW_RPT_SUPPLIER_PERFORMANCE
GO
CREATE VIEW dbo.VW_RPT_SUPPLIER_PERFORMANCE AS
SELECT
    S.SUPPLIER_CODE,
    S.SUPPLIER_NAME,
    S.OFFICE1_PHONE                    AS PHONE,
    S.OFFICE1_EMAIL_ID                 AS EMAIL,
    DATEPART(YEAR,  H.GRN_DATE)       AS YEAR,
    DATEPART(MONTH, H.GRN_DATE)       AS MONTH,
    DATENAME(MONTH, H.GRN_DATE)       AS MONTH_NAME,
    COUNT(DISTINCT H.GRN_NO)          AS TOTAL_GRNS,
    SUM(ISNULL(H.TOTALQTY,0))        AS TOTAL_QTY,
    SUM(ISNULL(H.GRANDTOTAL,0))      AS TOTAL_PURCHASE_VALUE,
    SUM(ISNULL(H.TOTALLINEDISCAMOUNT,0)) AS TOTAL_DISCOUNT,
    COUNT(DISTINCT PR.PRN_NO)         AS TOTAL_RETURNS,
    ISNULL(SUM(PR.GRANDTOTAL),0)     AS TOTAL_RETURN_VALUE
FROM dbo.SUPPLIER_MST S
LEFT JOIN dbo.GRN_HDR H  ON S.SUPPLIER_CODE=H.SUPPLIERCODE AND ISNULL(H.ISCANCELLED,0)=0
LEFT JOIN dbo.PRN_HDR PR ON S.SUPPLIER_CODE=PR.SUPPLIERCODE
GROUP BY S.SUPPLIER_CODE,S.SUPPLIER_NAME,S.OFFICE1_PHONE,S.OFFICE1_EMAIL_ID,
         DATEPART(YEAR,H.GRN_DATE),DATEPART(MONTH,H.GRN_DATE),DATENAME(MONTH,H.GRN_DATE)
GO

PRINT '== PHASE 1 COMPLETE: 16 Core Views Created =='
GO

-- ================================================================
-- PHASE 2: GST VIEWS
-- ================================================================
PRINT '== PHASE 2: GST COMPLIANCE VIEWS =='
GO

-- ────────────────────────────────────────────────────────────────
-- 17. HSN WISE SALES (GSTR-1 Table 12)
-- ────────────────────────────────────────────────────────────────
IF OBJECT_ID('dbo.VW_GST_HSN_SALES','V') IS NOT NULL DROP VIEW dbo.VW_GST_HSN_SALES
GO
CREATE VIEW dbo.VW_GST_HSN_SALES AS
SELECT
    DATEPART(YEAR,  H.BILL_DATE)                AS FIN_YEAR,
    DATEPART(MONTH, H.BILL_DATE)               AS TAX_MONTH,
    DATENAME(MONTH, H.BILL_DATE)               AS MONTH_NAME,
    H.SH_DEPT_CODE                             AS DEPT_CODE,
    ISNULL(D.HSNSACCODE,'UNKNOWN')             AS HSN_CODE,
    ISNULL(I.CONS_UOM,'NOS')                  AS UOM,
    COUNT(DISTINCT H.BILL_NO)                  AS BILL_COUNT,
    SUM(ISNULL(D.QTY,0))                      AS TOTAL_QTY,
    SUM(ISNULL(D.AMOUNT,0))                   AS TAXABLE_VALUE,
    SUM(ISNULL(D.DISC_AMOUNT,0))              AS TOTAL_DISCOUNT,
    SUM(ISNULL(D.AMOUNT,0)-ISNULL(D.DISC_AMOUNT,0)) AS NET_TAXABLE_VALUE,
    -- IGST (inter-state - simplified: where TAX_TYPE = 'IGST')
    SUM(CASE WHEN UPPER(ISNULL(D.TAX_TYPE,''))='IGST'
             THEN ISNULL(CAST(D.TAX_AMOUNT AS MONEY),0) ELSE 0 END) AS IGST_AMT,
    -- CGST = half of non-IGST tax
    SUM(CASE WHEN UPPER(ISNULL(D.TAX_TYPE,''))<>'IGST'
             THEN ISNULL(CAST(D.TAX_AMOUNT AS MONEY),0)/2 ELSE 0 END) AS CGST_AMT,
    -- SGST = half of non-IGST tax
    SUM(CASE WHEN UPPER(ISNULL(D.TAX_TYPE,''))<>'IGST'
             THEN ISNULL(CAST(D.TAX_AMOUNT AS MONEY),0)/2 ELSE 0 END) AS SGST_AMT,
    SUM(ISNULL(CAST(D.CESS_AMOUNT AS MONEY),0))  AS CESS_AMT,
    SUM(ISNULL(CAST(D.TAX_AMOUNT AS MONEY),0))   AS TOTAL_TAX,
    SUM(ISNULL(D.TOTAL,0))                        AS TOTAL_VALUE,
    AVG(ISNULL(D.TAX_PERCENT,0))                  AS GST_RATE
FROM dbo.SALES_HDR H
INNER JOIN dbo.SALES_DTL D ON H.BILL_NO=D.BILL_NO AND H.SH_DEPT_CODE=D.SD_DEPT_CODE
LEFT  JOIN dbo.ITEM_MST I  ON D.SERVICEORPRODUCTCODE=I.ITEM_CODE
WHERE ISNULL(H.ISCANCELLED,0)=0
  AND D.SALES_ITEM_TYPE='P'
  AND ISNULL(D.HSNSACCODE,'')<>''
GROUP BY DATEPART(YEAR,H.BILL_DATE),DATEPART(MONTH,H.BILL_DATE),
         DATENAME(MONTH,H.BILL_DATE),H.SH_DEPT_CODE,
         ISNULL(D.HSNSACCODE,'UNKNOWN'),ISNULL(I.CONS_UOM,'NOS')
GO

-- ────────────────────────────────────────────────────────────────
-- 18. HSN WISE PURCHASE (GSTR-2)
-- ────────────────────────────────────────────────────────────────
IF OBJECT_ID('dbo.VW_GST_HSN_PURCHASE','V') IS NOT NULL DROP VIEW dbo.VW_GST_HSN_PURCHASE
GO
CREATE VIEW dbo.VW_GST_HSN_PURCHASE AS
SELECT
    DATEPART(YEAR,  H.GRN_DATE)               AS FIN_YEAR,
    DATEPART(MONTH, H.GRN_DATE)               AS TAX_MONTH,
    DATENAME(MONTH, H.GRN_DATE)               AS MONTH_NAME,
    H.GH_DEPT_CODE                             AS DEPT_CODE,
    ISNULL(D.HSNSACCODE,'UNKNOWN')             AS HSN_CODE,
    ISNULL(I.PUR_UOM,'NOS')                   AS UOM,
    S.SUPPLIER_NAME,
    S.GSTIN_NO                                 AS SUPPLIER_GSTIN,
    COUNT(DISTINCT H.GRN_NO)                   AS GRN_COUNT,
    SUM(ISNULL(D.REC_QTY,0))                  AS TOTAL_QTY,
    SUM(ISNULL(D.AMOUNT,0))                   AS TAXABLE_VALUE,
    SUM(ISNULL(D.TAX_AMOUNT,0))              AS TOTAL_TAX,
    SUM(ISNULL(D.TAX_AMOUNT,0)/2)            AS CGST_AMT,
    SUM(ISNULL(D.TAX_AMOUNT,0)/2)            AS SGST_AMT,
    SUM(ISNULL(CAST(D.CESS_AMOUNT AS MONEY),0)) AS CESS_AMT,
    SUM(ISNULL(D.AMOUNT,0)+ISNULL(D.TAX_AMOUNT,0)) AS TOTAL_VALUE,
    AVG(ISNULL(D.TAX_PERCENT,0))              AS GST_RATE,
    CASE WHEN S.GSTIN_NO IS NOT NULL AND LEN(ISNULL(S.GSTIN_NO,''))=15
         THEN 'ELIGIBLE' ELSE 'INELIGIBLE' END AS ITC_STATUS
FROM dbo.GRN_HDR H
INNER JOIN dbo.GRN_DTL D    ON H.GRN_NO=D.GRN_NO AND H.GH_DEPT_CODE=D.GD_DEPT_CODE
LEFT  JOIN dbo.SUPPLIER_MST S   ON H.SUPPLIERCODE=S.SUPPLIER_CODE
LEFT  JOIN dbo.ITEM_MST I       ON D.ITEM_CODE=I.ITEM_CODE
WHERE ISNULL(H.ISCANCELLED,0)=0
GROUP BY DATEPART(YEAR,H.GRN_DATE),DATEPART(MONTH,H.GRN_DATE),
         DATENAME(MONTH,H.GRN_DATE),H.GH_DEPT_CODE,
         ISNULL(D.HSNSACCODE,'UNKNOWN'),ISNULL(I.PUR_UOM,'NOS'),
         S.SUPPLIER_NAME,S.GSTIN_NO
GO

-- ────────────────────────────────────────────────────────────────
-- 19. GSTR-1 DETAIL (B2B / B2C)
-- ────────────────────────────────────────────────────────────────
IF OBJECT_ID('dbo.VW_GST_GSTR1','V') IS NOT NULL DROP VIEW dbo.VW_GST_GSTR1
GO
CREATE VIEW dbo.VW_GST_GSTR1 AS
SELECT
    DATEPART(YEAR,  H.BILL_DATE)               AS FIN_YEAR,
    DATEPART(MONTH, H.BILL_DATE)               AS TAX_MONTH,
    DATENAME(MONTH, H.BILL_DATE)               AS MONTH_NAME,
    H.SH_DEPT_CODE                             AS DEPT_CODE,
    H.BILL_NO,
    CONVERT(DATE, H.BILL_DATE)                 AS BILL_DATE,
    ISNULL(H.GSTBILLNO, CAST(H.BILL_NO AS VARCHAR)) AS GST_INVOICE_NO,
    H.INVOICE_TPE                              AS INVOICE_TYPE,
    H.CUSTOMER_CODE,
    H.CUSTOMER                                 AS CUSTOMER_NAME,
    -- B2B if customer has GSTIN (not stored here - classify by value)
    CASE WHEN ISNULL(H.GRAND_TOTAL,0)>=250000 THEN 'B2CL'
         WHEN H.CUSTOMER_CODE>0 THEN 'B2B'
         ELSE 'B2CS' END                        AS INVOICE_CATEGORY,
    SUM(ISNULL(D.AMOUNT,0)-ISNULL(D.DISC_AMOUNT,0)) AS TAXABLE_VALUE,
    SUM(CASE WHEN UPPER(ISNULL(D.TAX_TYPE,''))='IGST'
             THEN ISNULL(CAST(D.TAX_AMOUNT AS MONEY),0) ELSE 0 END) AS IGST_AMT,
    SUM(CASE WHEN UPPER(ISNULL(D.TAX_TYPE,''))<>'IGST'
             THEN ISNULL(CAST(D.TAX_AMOUNT AS MONEY),0)/2 ELSE 0 END) AS CGST_AMT,
    SUM(CASE WHEN UPPER(ISNULL(D.TAX_TYPE,''))<>'IGST'
             THEN ISNULL(CAST(D.TAX_AMOUNT AS MONEY),0)/2 ELSE 0 END) AS SGST_AMT,
    SUM(ISNULL(CAST(D.CESS_AMOUNT AS MONEY),0))  AS CESS_AMT,
    SUM(ISNULL(CAST(D.TAX_AMOUNT AS MONEY),0))   AS TOTAL_TAX,
    ISNULL(H.GRAND_TOTAL,0)                       AS INVOICE_VALUE
FROM dbo.SALES_HDR H
INNER JOIN dbo.SALES_DTL D ON H.BILL_NO=D.BILL_NO AND H.SH_DEPT_CODE=D.SD_DEPT_CODE
WHERE ISNULL(H.ISCANCELLED,0)=0
GROUP BY DATEPART(YEAR,H.BILL_DATE),DATEPART(MONTH,H.BILL_DATE),
         DATENAME(MONTH,H.BILL_DATE),H.SH_DEPT_CODE,H.BILL_NO,
         CONVERT(DATE,H.BILL_DATE),ISNULL(H.GSTBILLNO,CAST(H.BILL_NO AS VARCHAR)),
         H.INVOICE_TPE,H.CUSTOMER_CODE,H.CUSTOMER,H.GRAND_TOTAL
GO

-- ────────────────────────────────────────────────────────────────
-- 20. GSTR-3B MONTHLY SUMMARY
-- ────────────────────────────────────────────────────────────────
IF OBJECT_ID('dbo.VW_GST_GSTR3B','V') IS NOT NULL DROP VIEW dbo.VW_GST_GSTR3B
GO
CREATE VIEW dbo.VW_GST_GSTR3B AS
SELECT
    DATEPART(YEAR,  H.BILL_DATE)               AS FIN_YEAR,
    DATEPART(MONTH, H.BILL_DATE)               AS TAX_MONTH,
    DATENAME(MONTH, H.BILL_DATE)               AS MONTH_NAME,
    H.SH_DEPT_CODE                             AS DEPT_CODE,
    -- 3.1(a) Outward taxable supplies
    SUM(ISNULL(D.AMOUNT,0)-ISNULL(D.DISC_AMOUNT,0)) AS TAXABLE_OUTWARD,
    SUM(CASE WHEN UPPER(ISNULL(D.TAX_TYPE,''))='IGST'
             THEN ISNULL(CAST(D.TAX_AMOUNT AS MONEY),0) ELSE 0 END) AS OUT_IGST,
    SUM(CASE WHEN UPPER(ISNULL(D.TAX_TYPE,''))<>'IGST'
             THEN ISNULL(CAST(D.TAX_AMOUNT AS MONEY),0)/2 ELSE 0 END) AS OUT_CGST,
    SUM(CASE WHEN UPPER(ISNULL(D.TAX_TYPE,''))<>'IGST'
             THEN ISNULL(CAST(D.TAX_AMOUNT AS MONEY),0)/2 ELSE 0 END) AS OUT_SGST,
    SUM(ISNULL(CAST(D.CESS_AMOUNT AS MONEY),0))  AS OUT_CESS,
    -- Nil rated / exempt
    SUM(CASE WHEN ISNULL(D.TAX_PERCENT,0)=0
             THEN ISNULL(D.AMOUNT,0) ELSE 0 END) AS NIL_RATED_SUPPLY,
    -- Total tax liability
    SUM(ISNULL(CAST(D.TAX_AMOUNT AS MONEY),0))   AS TOTAL_TAX_LIABILITY,
    -- Total invoice value
    SUM(ISNULL(H.GRAND_TOTAL,0))                  AS TOTAL_INVOICE_VALUE,
    COUNT(DISTINCT H.BILL_NO)                      AS INVOICE_COUNT
FROM dbo.SALES_HDR H
INNER JOIN dbo.SALES_DTL D ON H.BILL_NO=D.BILL_NO AND H.SH_DEPT_CODE=D.SD_DEPT_CODE
WHERE ISNULL(H.ISCANCELLED,0)=0
GROUP BY DATEPART(YEAR,H.BILL_DATE),DATEPART(MONTH,H.BILL_DATE),
         DATENAME(MONTH,H.BILL_DATE),H.SH_DEPT_CODE
GO

-- ────────────────────────────────────────────────────────────────
-- 21. ITC (Input Tax Credit) DETAIL
-- ────────────────────────────────────────────────────────────────
IF OBJECT_ID('dbo.VW_GST_ITC_DETAIL','V') IS NOT NULL DROP VIEW dbo.VW_GST_ITC_DETAIL
GO
CREATE VIEW dbo.VW_GST_ITC_DETAIL AS
SELECT
    DATEPART(YEAR,  H.GRN_DATE)               AS FIN_YEAR,
    DATEPART(MONTH, H.GRN_DATE)               AS TAX_MONTH,
    DATENAME(MONTH, H.GRN_DATE)               AS MONTH_NAME,
    H.GH_DEPT_CODE                             AS DEPT_CODE,
    H.GRN_NO,
    CONVERT(DATE, H.GRN_DATE)                 AS GRN_DATE,
    H.INVOICENO                                AS SUPPLIER_INVOICE,
    CONVERT(DATE, H.INVOICE_DATE)             AS INVOICE_DATE,
    H.SUPPLIERCODE,
    S.SUPPLIER_NAME,
    S.GSTIN_NO                                 AS SUPPLIER_GSTIN,
    S.PAN_NO                                   AS SUPPLIER_PAN,
    SUM(ISNULL(D.AMOUNT,0))                   AS TAXABLE_VALUE,
    SUM(ISNULL(D.TAX_AMOUNT,0))              AS TOTAL_TAX,
    SUM(ISNULL(D.TAX_AMOUNT,0)/2)            AS CGST_ITC,
    SUM(ISNULL(D.TAX_AMOUNT,0)/2)            AS SGST_ITC,
    SUM(ISNULL(CAST(D.CESS_AMOUNT AS MONEY),0)) AS CESS_ITC,
    CASE WHEN S.GSTIN_NO IS NOT NULL AND LEN(ISNULL(S.GSTIN_NO,''))=15
         THEN 'ELIGIBLE'
         ELSE 'INELIGIBLE - NO GSTIN' END      AS ITC_ELIGIBILITY,
    CASE WHEN S.GSTIN_NO IS NOT NULL AND LEN(ISNULL(S.GSTIN_NO,''))=15
         THEN SUM(ISNULL(D.TAX_AMOUNT,0)) ELSE 0 END AS ELIGIBLE_ITC,
    CASE WHEN S.GSTIN_NO IS NULL OR LEN(ISNULL(S.GSTIN_NO,''))<>15
         THEN SUM(ISNULL(D.TAX_AMOUNT,0)) ELSE 0 END AS INELIGIBLE_ITC
FROM dbo.GRN_HDR H
INNER JOIN dbo.GRN_DTL D    ON H.GRN_NO=D.GRN_NO AND H.GH_DEPT_CODE=D.GD_DEPT_CODE
LEFT  JOIN dbo.SUPPLIER_MST S   ON H.SUPPLIERCODE=S.SUPPLIER_CODE
WHERE ISNULL(H.ISCANCELLED,0)=0
GROUP BY DATEPART(YEAR,H.GRN_DATE),DATEPART(MONTH,H.GRN_DATE),
         DATENAME(MONTH,H.GRN_DATE),H.GH_DEPT_CODE,H.GRN_NO,
         CONVERT(DATE,H.GRN_DATE),H.INVOICENO,CONVERT(DATE,H.INVOICE_DATE),
         H.SUPPLIERCODE,S.SUPPLIER_NAME,S.GSTIN_NO,S.PAN_NO
GO

-- ────────────────────────────────────────────────────────────────
-- 22. CREDIT/DEBIT NOTE (CDNR)
-- ────────────────────────────────────────────────────────────────
IF OBJECT_ID('dbo.VW_GST_CDNR','V') IS NOT NULL DROP VIEW dbo.VW_GST_CDNR
GO
CREATE VIEW dbo.VW_GST_CDNR AS
SELECT
    DATEPART(YEAR,  RH.BILL_RTN_DATE)          AS FIN_YEAR,
    DATEPART(MONTH, RH.BILL_RTN_DATE)          AS TAX_MONTH,
    DATENAME(MONTH, RH.BILL_RTN_DATE)          AS MONTH_NAME,
    RH.SRH_DEPT_CODE                            AS DEPT_CODE,
    RH.BILL_RTN_NO                              AS NOTE_NUMBER,
    CONVERT(DATE, RH.BILL_RTN_DATE)            AS NOTE_DATE,
    RH.AGAINST_BILL_NO                          AS ORIGINAL_INVOICE,
    'CREDIT NOTE'                               AS NOTE_TYPE,
    SUM(ISNULL(RD.AMOUNT,0))                  AS TAXABLE_VALUE,
    SUM(ISNULL(CAST(RD.TAX_AMOUNT AS MONEY),0)) AS TOTAL_TAX,
    SUM(ISNULL(CAST(RD.TAX_AMOUNT AS MONEY),0)/2) AS CGST_AMT,
    SUM(ISNULL(CAST(RD.TAX_AMOUNT AS MONEY),0)/2) AS SGST_AMT,
    ISNULL(RH.GRAND_TOTAL,0)                   AS NOTE_VALUE,
    RH.REASON_FOR_REFUND                        AS REASON
FROM dbo.SALES_RETURN_HDR RH
INNER JOIN dbo.SALES_RETURN_DTL RD ON RH.BILL_RTN_NO=RD.BILL_RTN_NO
                                   AND RH.SRH_DEPT_CODE=RD.SRD_DEPT_CODE
GROUP BY DATEPART(YEAR,RH.BILL_RTN_DATE),DATEPART(MONTH,RH.BILL_RTN_DATE),
         DATENAME(MONTH,RH.BILL_RTN_DATE),RH.SRH_DEPT_CODE,RH.BILL_RTN_NO,
         CONVERT(DATE,RH.BILL_RTN_DATE),RH.AGAINST_BILL_NO,
         RH.GRAND_TOTAL,RH.REASON_FOR_REFUND
GO

PRINT '== PHASE 2 COMPLETE: 6 GST Views Created =='
GO

-- ================================================================
-- PHASE 3: ADVANCED ANALYTICS VIEWS
-- ================================================================
PRINT '== PHASE 3: ADVANCED ANALYTICS VIEWS =='
GO

-- ────────────────────────────────────────────────────────────────
-- 23. CUSTOMER TREND (monthly buying pattern)
-- ────────────────────────────────────────────────────────────────
IF OBJECT_ID('dbo.VW_RPT_CUSTOMER_TREND','V') IS NOT NULL DROP VIEW dbo.VW_RPT_CUSTOMER_TREND
GO
CREATE VIEW dbo.VW_RPT_CUSTOMER_TREND AS
SELECT
    H.CUSTOMER_CODE,
    CM.CUSTOMER_NAME,
    CM.OFFICE1_PHONE                   AS MOBILE,
    ISNULL(CM.VIP_CUSTOMER,0)         AS IS_VIP,
    DATEPART(YEAR,  H.BILL_DATE)      AS YEAR,
    DATEPART(MONTH, H.BILL_DATE)      AS MONTH,
    DATENAME(MONTH, H.BILL_DATE)      AS MONTH_NAME,
    H.SH_DEPT_CODE                     AS DEPT_CODE,
    COUNT(DISTINCT H.BILL_NO)          AS VISIT_COUNT,
    SUM(ISNULL(H.GRAND_TOTAL,0))      AS TOTAL_SPENT,
    AVG(ISNULL(H.GRAND_TOTAL,0))      AS AVG_BILL,
    MAX(ISNULL(H.GRAND_TOTAL,0))      AS MAX_BILL,
    SUM(ISNULL(H.DISC_AMOUNT,0))     AS TOTAL_DISCOUNT,
    SUM(ISNULL(H.RedeemAmt,0))       AS TOTAL_REDEEMED,
    MAX(CONVERT(DATE,H.BILL_DATE))    AS LAST_PURCHASE_DATE,
    DATEDIFF(DAY, MAX(CONVERT(DATE,H.BILL_DATE)), CAST(GETDATE() AS DATE)) AS DAYS_SINCE_LAST_VISIT
FROM dbo.SALES_HDR H
INNER JOIN dbo.CUSTOMER_MST CM ON H.CUSTOMER_CODE=CM.CUSTOMER_CODE
WHERE ISNULL(H.ISCANCELLED,0)=0
  AND H.CUSTOMER_CODE IS NOT NULL AND H.CUSTOMER_CODE>0
GROUP BY H.CUSTOMER_CODE,CM.CUSTOMER_NAME,CM.OFFICE1_PHONE,
         ISNULL(CM.VIP_CUSTOMER,0),DATEPART(YEAR,H.BILL_DATE),
         DATEPART(MONTH,H.BILL_DATE),DATENAME(MONTH,H.BILL_DATE),H.SH_DEPT_CODE
GO

-- ────────────────────────────────────────────────────────────────
-- 24. CUSTOMER SEGMENTS (RFM-style)
-- ────────────────────────────────────────────────────────────────
IF OBJECT_ID('dbo.VW_RPT_CUSTOMER_SEGMENTS','V') IS NOT NULL DROP VIEW dbo.VW_RPT_CUSTOMER_SEGMENTS
GO
CREATE VIEW dbo.VW_RPT_CUSTOMER_SEGMENTS AS
SELECT
    H.CUSTOMER_CODE,
    CM.CUSTOMER_NAME,
    CM.OFFICE1_PHONE                   AS MOBILE,
    CM.OFFICE1_EMAIL_ID               AS EMAIL,
    ISNULL(CM.VIP_CUSTOMER,0)         AS IS_VIP,
    CM.OFFICE1_CITY                   AS CITY,
    COUNT(DISTINCT H.BILL_NO)          AS TOTAL_VISITS,
    SUM(ISNULL(H.GRAND_TOTAL,0))      AS LIFETIME_VALUE,
    AVG(ISNULL(H.GRAND_TOTAL,0))      AS AVG_BILL_VALUE,
    MAX(CONVERT(DATE,H.BILL_DATE))     AS LAST_VISIT,
    MIN(CONVERT(DATE,H.BILL_DATE))     AS FIRST_VISIT,
    DATEDIFF(DAY,MAX(CONVERT(DATE,H.BILL_DATE)),CAST(GETDATE() AS DATE)) AS DAYS_INACTIVE,
    ISNULL(CM.BALANCE_POINTS,0)       AS LOYALTY_POINTS,
    -- Segment logic
    CASE
        WHEN DATEDIFF(DAY,MAX(CONVERT(DATE,H.BILL_DATE)),CAST(GETDATE() AS DATE))<=30
             AND SUM(ISNULL(H.GRAND_TOTAL,0))>=10000 THEN 'CHAMPION'
        WHEN DATEDIFF(DAY,MAX(CONVERT(DATE,H.BILL_DATE)),CAST(GETDATE() AS DATE))<=30 THEN 'LOYAL'
        WHEN DATEDIFF(DAY,MAX(CONVERT(DATE,H.BILL_DATE)),CAST(GETDATE() AS DATE))<=90
             AND SUM(ISNULL(H.GRAND_TOTAL,0))>=5000 THEN 'POTENTIAL LOYALIST'
        WHEN DATEDIFF(DAY,MAX(CONVERT(DATE,H.BILL_DATE)),CAST(GETDATE() AS DATE))<=90 THEN 'RECENT'
        WHEN DATEDIFF(DAY,MAX(CONVERT(DATE,H.BILL_DATE)),CAST(GETDATE() AS DATE))<=180 THEN 'AT RISK'
        WHEN DATEDIFF(DAY,MAX(CONVERT(DATE,H.BILL_DATE)),CAST(GETDATE() AS DATE))<=365 THEN 'DORMANT'
        ELSE 'LOST'
    END AS CUSTOMER_SEGMENT
FROM dbo.SALES_HDR H
INNER JOIN dbo.CUSTOMER_MST CM ON H.CUSTOMER_CODE=CM.CUSTOMER_CODE
WHERE ISNULL(H.ISCANCELLED,0)=0
  AND H.CUSTOMER_CODE IS NOT NULL AND H.CUSTOMER_CODE>0
GROUP BY H.CUSTOMER_CODE,CM.CUSTOMER_NAME,CM.OFFICE1_PHONE,
         CM.OFFICE1_EMAIL_ID,ISNULL(CM.VIP_CUSTOMER,0),
         CM.OFFICE1_CITY,ISNULL(CM.BALANCE_POINTS,0)
GO

-- ────────────────────────────────────────────────────────────────
-- 25. ITEM VELOCITY (fast/slow moving)
-- ────────────────────────────────────────────────────────────────
IF OBJECT_ID('dbo.VW_RPT_ITEM_VELOCITY','V') IS NOT NULL DROP VIEW dbo.VW_RPT_ITEM_VELOCITY
GO
CREATE VIEW dbo.VW_RPT_ITEM_VELOCITY AS
SELECT
    D.SD_DEPT_CODE                     AS DEPT_CODE,
    D.SERVICEORPRODUCTCODE             AS ITEM_CODE,
    I.ITEM_NAME,
    I.EAN_CODE,
    CAT.Category_Desc                  AS CATEGORY,
    BRD.Brand_Name                     AS BRAND,
    S.SUPPLIER_NAME,
    ISNULL(I.QOH,0)                   AS CURRENT_STOCK,
    COUNT(DISTINCT H.BILL_NO)          AS BILLS_COUNT,
    COUNT(DISTINCT CONVERT(DATE,H.BILL_DATE)) AS DAYS_SOLD,
    SUM(ISNULL(D.QTY,0))             AS TOTAL_QTY_SOLD,
    SUM(ISNULL(D.AMOUNT,0))          AS TOTAL_REVENUE,
    AVG(ISNULL(D.QTY,0))             AS AVG_QTY_PER_BILL,
    MAX(CONVERT(DATE,H.BILL_DATE))    AS LAST_SOLD_DATE,
    DATEDIFF(DAY,MAX(CONVERT(DATE,H.BILL_DATE)),CAST(GETDATE() AS DATE)) AS DAYS_SINCE_SOLD,
    -- Daily average sales
    CASE WHEN DATEDIFF(DAY,MIN(CONVERT(DATE,H.BILL_DATE)),MAX(CONVERT(DATE,H.BILL_DATE)))>0
         THEN SUM(ISNULL(D.QTY,0)) / DATEDIFF(DAY,MIN(CONVERT(DATE,H.BILL_DATE)),CAST(GETDATE() AS DATE))
         ELSE SUM(ISNULL(D.QTY,0)) END AS DAILY_AVG_SALES,
    -- Velocity classification
    CASE
        WHEN SUM(ISNULL(D.QTY,0)) >= 100 AND DATEDIFF(DAY,MAX(CONVERT(DATE,H.BILL_DATE)),CAST(GETDATE() AS DATE))<=30 THEN 'FAST MOVING'
        WHEN SUM(ISNULL(D.QTY,0)) >= 20  AND DATEDIFF(DAY,MAX(CONVERT(DATE,H.BILL_DATE)),CAST(GETDATE() AS DATE))<=60 THEN 'MEDIUM MOVING'
        WHEN DATEDIFF(DAY,MAX(CONVERT(DATE,H.BILL_DATE)),CAST(GETDATE() AS DATE))>180 THEN 'DEAD STOCK'
        ELSE 'SLOW MOVING'
    END AS VELOCITY
FROM dbo.SALES_DTL D
INNER JOIN dbo.SALES_HDR H      ON D.BILL_NO=H.BILL_NO AND D.SD_DEPT_CODE=H.SH_DEPT_CODE
LEFT  JOIN dbo.ITEM_MST I       ON D.SERVICEORPRODUCTCODE=I.ITEM_CODE
LEFT  JOIN dbo.Category_Mst CAT ON I.CATEGORY_CODE=CAT.Category_Code
LEFT  JOIN dbo.Brand_Master BRD ON I.BRAND_CODE=BRD.Brand_Code
LEFT  JOIN dbo.SUPPLIER_MST S   ON I.SUPPLIER_CODE=S.SUPPLIER_CODE
WHERE ISNULL(H.ISCANCELLED,0)=0 AND D.SALES_ITEM_TYPE='P'
GROUP BY D.SD_DEPT_CODE,D.SERVICEORPRODUCTCODE,I.ITEM_NAME,I.EAN_CODE,
         CAT.Category_Desc,BRD.Brand_Name,S.SUPPLIER_NAME,ISNULL(I.QOH,0)
GO

-- ────────────────────────────────────────────────────────────────
-- 26. PROFITABILITY (item + customer wise)
-- ────────────────────────────────────────────────────────────────
IF OBJECT_ID('dbo.VW_RPT_PROFITABILITY','V') IS NOT NULL DROP VIEW dbo.VW_RPT_PROFITABILITY
GO
CREATE VIEW dbo.VW_RPT_PROFITABILITY AS
SELECT
    H.SH_DEPT_CODE                     AS DEPT_CODE,
    DATEPART(YEAR,  H.BILL_DATE)      AS YEAR,
    DATEPART(MONTH, H.BILL_DATE)      AS MONTH,
    DATENAME(MONTH, H.BILL_DATE)      AS MONTH_NAME,
    D.SERVICEORPRODUCTCODE             AS ITEM_CODE,
    I.ITEM_NAME,
    CAT.Category_Desc                  AS CATEGORY,
    BRD.Brand_Name                     AS BRAND,
    H.CUSTOMER_CODE,
    H.CUSTOMER                         AS CUSTOMER_NAME,
    SUM(ISNULL(D.QTY,0))             AS QTY_SOLD,
    SUM(ISNULL(D.AMOUNT,0))          AS REVENUE,
    SUM(ISNULL(D.ORG_CP,0)*ISNULL(D.QTY,0)) AS COST_OF_GOODS,
    SUM(ISNULL(D.DISC_AMOUNT,0))     AS DISCOUNT_GIVEN,
    SUM(ISNULL(D.AMOUNT,0)) - SUM(ISNULL(D.ORG_CP,0)*ISNULL(D.QTY,0)) AS GROSS_PROFIT,
    CASE WHEN SUM(ISNULL(D.AMOUNT,0))>0
         THEN (SUM(ISNULL(D.AMOUNT,0))-SUM(ISNULL(D.ORG_CP,0)*ISNULL(D.QTY,0)))
              / SUM(ISNULL(D.AMOUNT,0)) * 100
         ELSE 0 END                    AS MARGIN_PCT,
    SUM(ISNULL(CAST(D.TAX_AMOUNT AS MONEY),0)) AS GST_COLLECTED
FROM dbo.SALES_HDR H
INNER JOIN dbo.SALES_DTL D      ON H.BILL_NO=D.BILL_NO AND H.SH_DEPT_CODE=D.SD_DEPT_CODE
LEFT  JOIN dbo.ITEM_MST I       ON D.SERVICEORPRODUCTCODE=I.ITEM_CODE
LEFT  JOIN dbo.Category_Mst CAT ON I.CATEGORY_CODE=CAT.Category_Code
LEFT  JOIN dbo.Brand_Master BRD ON I.BRAND_CODE=BRD.Brand_Code
WHERE ISNULL(H.ISCANCELLED,0)=0 AND D.SALES_ITEM_TYPE='P'
GROUP BY H.SH_DEPT_CODE,DATEPART(YEAR,H.BILL_DATE),DATEPART(MONTH,H.BILL_DATE),
         DATENAME(MONTH,H.BILL_DATE),D.SERVICEORPRODUCTCODE,I.ITEM_NAME,
         CAT.Category_Desc,BRD.Brand_Name,H.CUSTOMER_CODE,H.CUSTOMER
GO

-- ────────────────────────────────────────────────────────────────
-- 27. SALES vs PURCHASE (month comparison)
-- ────────────────────────────────────────────────────────────────
IF OBJECT_ID('dbo.VW_RPT_SALES_VS_PURCHASE','V') IS NOT NULL DROP VIEW dbo.VW_RPT_SALES_VS_PURCHASE
GO
CREATE VIEW dbo.VW_RPT_SALES_VS_PURCHASE AS
SELECT
    DATEPART(YEAR,  S.BILL_DATE)      AS YEAR,
    DATEPART(MONTH, S.BILL_DATE)      AS MONTH,
    DATENAME(MONTH, S.BILL_DATE)      AS MONTH_NAME,
    S.SH_DEPT_CODE                     AS DEPT_CODE,
    SUM(ISNULL(S.GRAND_TOTAL,0))      AS TOTAL_SALES,
    SUM(ISNULL(S.DISC_AMOUNT,0))     AS SALES_DISCOUNT,
    COUNT(DISTINCT S.BILL_NO)          AS SALES_BILLS
FROM dbo.SALES_HDR S
WHERE ISNULL(S.ISCANCELLED,0)=0
GROUP BY DATEPART(YEAR,S.BILL_DATE),DATEPART(MONTH,S.BILL_DATE),
         DATENAME(MONTH,S.BILL_DATE),S.SH_DEPT_CODE
GO

-- ────────────────────────────────────────────────────────────────
-- 28. EXCEPTIONS (negative stock, abnormal sales, cancelled bills)
-- ────────────────────────────────────────────────────────────────
IF OBJECT_ID('dbo.VW_RPT_EXCEPTIONS','V') IS NOT NULL DROP VIEW dbo.VW_RPT_EXCEPTIONS
GO
CREATE VIEW dbo.VW_RPT_EXCEPTIONS AS
-- Negative / zero stock items
SELECT
    'NEGATIVE STOCK'                   AS EXCEPTION_TYPE,
    'HIGH'                             AS SEVERITY,
    CAST(ITEM_CODE AS VARCHAR)         AS REFERENCE_NO,
    ITEM_NAME                          AS DESCRIPTION,
    CAST(QOH AS VARCHAR)               AS AMOUNT_STR,
    GETDATE()                          AS EXCEPTION_DATE,
    NULL                               AS DEPT_CODE
FROM dbo.ITEM_MST
WHERE ISNULL(QOH,0)<0 AND ISNULL(Discontinue,0)=0
UNION ALL
-- High value cancelled bills
SELECT
    'CANCELLED HIGH VALUE BILL',
    'HIGH',
    CAST(BILL_NO AS VARCHAR),
    'Bill cancelled: ' + ISNULL(REASON_FOR_CANCELLATION,'No reason'),
    CAST(ISNULL(GRAND_TOTAL,0) AS VARCHAR),
    CANCELLED_DATE,
    SH_DEPT_CODE
FROM dbo.SALES_HDR
WHERE ISNULL(ISCANCELLED,0)=1 AND ISNULL(GRAND_TOTAL,0)>5000
UNION ALL
-- Items with stock below reorder
SELECT
    'REORDER ALERT',
    'MEDIUM',
    CAST(ITEM_CODE AS VARCHAR),
    ITEM_NAME,
    'QOH:' + CAST(ISNULL(QOH,0) AS VARCHAR) + ' REORDER:' + CAST(ISNULL(REORDER_LVL,0) AS VARCHAR),
    GETDATE(),
    NULL
FROM dbo.ITEM_MST
WHERE ISNULL(QOH,0)<=ISNULL(REORDER_LVL,0) AND ISNULL(REORDER_LVL,0)>0
  AND ISNULL(Discontinue,0)=0
GO

-- ────────────────────────────────────────────────────────────────
-- 29. STOCK VALUATION
-- ────────────────────────────────────────────────────────────────
IF OBJECT_ID('dbo.VW_RPT_STOCK_VALUATION','V') IS NOT NULL DROP VIEW dbo.VW_RPT_STOCK_VALUATION
GO
CREATE VIEW dbo.VW_RPT_STOCK_VALUATION AS
SELECT
    I.ITEM_CODE,
    I.ITEM_NAME,
    I.EAN_CODE,
    CAT.Category_Desc                  AS CATEGORY,
    BRD.Brand_Name                     AS BRAND,
    S.SUPPLIER_NAME,
    ISNULL(I.QOH,0)                   AS QTY_ON_HAND,
    ISNULL(I.CP,0)                    AS COST_PRICE,
    ISNULL(I.MRP,0)                   AS MRP,
    ISNULL(I.SP,0)                    AS SALE_PRICE,
    ISNULL(I.QOH,0)*ISNULL(I.CP,0)   AS VALUE_AT_COST,
    ISNULL(I.QOH,0)*ISNULL(I.MRP,0)  AS VALUE_AT_MRP,
    ISNULL(I.QOH,0)*ISNULL(I.SP,0)   AS VALUE_AT_SP,
    (ISNULL(I.QOH,0)*ISNULL(I.SP,0)) -
    (ISNULL(I.QOH,0)*ISNULL(I.CP,0)) AS POTENTIAL_PROFIT,
    I.HSN_CODE,
    I.EXP_DATE                         AS EXPIRY_DATE,
    CASE WHEN I.EXP_DATE IS NOT NULL AND I.EXP_DATE<GETDATE() THEN 'EXPIRED'
         WHEN I.EXP_DATE IS NOT NULL AND I.EXP_DATE<DATEADD(DAY,30,GETDATE()) THEN 'EXPIRING SOON'
         ELSE 'OK' END AS EXPIRY_STATUS
FROM dbo.ITEM_MST I
LEFT JOIN dbo.Category_Mst CAT  ON I.CATEGORY_CODE=CAT.Category_Code
LEFT JOIN dbo.Brand_Master BRD  ON I.BRAND_CODE=BRD.Brand_Code
LEFT JOIN dbo.SUPPLIER_MST S    ON I.SUPPLIER_CODE=S.SUPPLIER_CODE
WHERE ISNULL(I.Discontinue,0)=0 AND ISNULL(I.QOH,0)>0
GO

-- ────────────────────────────────────────────────────────────────
-- 30. LIVE DASHBOARD SUMMARY
-- ────────────────────────────────────────────────────────────────
IF OBJECT_ID('dbo.VW_RPT_DASHBOARD','V') IS NOT NULL DROP VIEW dbo.VW_RPT_DASHBOARD
GO
CREATE VIEW dbo.VW_RPT_DASHBOARD AS
SELECT
    CAST(GETDATE() AS DATE)            AS REPORT_DATE,
    -- Today sales
    (SELECT COUNT(*) FROM dbo.SALES_HDR WHERE CONVERT(DATE,BILL_DATE)=CAST(GETDATE() AS DATE) AND ISNULL(ISCANCELLED,0)=0) AS TODAY_BILLS,
    (SELECT ISNULL(SUM(GRAND_TOTAL),0) FROM dbo.SALES_HDR WHERE CONVERT(DATE,BILL_DATE)=CAST(GETDATE() AS DATE) AND ISNULL(ISCANCELLED,0)=0) AS TODAY_SALES,
    (SELECT ISNULL(SUM(DISC_AMOUNT),0) FROM dbo.SALES_HDR WHERE CONVERT(DATE,BILL_DATE)=CAST(GETDATE() AS DATE) AND ISNULL(ISCANCELLED,0)=0) AS TODAY_DISCOUNT,
    -- This month
    (SELECT ISNULL(SUM(GRAND_TOTAL),0) FROM dbo.SALES_HDR WHERE YEAR(BILL_DATE)=YEAR(GETDATE()) AND MONTH(BILL_DATE)=MONTH(GETDATE()) AND ISNULL(ISCANCELLED,0)=0) AS MTD_SALES,
    (SELECT COUNT(*) FROM dbo.SALES_HDR WHERE YEAR(BILL_DATE)=YEAR(GETDATE()) AND MONTH(BILL_DATE)=MONTH(GETDATE()) AND ISNULL(ISCANCELLED,0)=0) AS MTD_BILLS,
    -- Stock
    (SELECT COUNT(*) FROM dbo.ITEM_MST WHERE ISNULL(QOH,0)<=0 AND ISNULL(Discontinue,0)=0) AS OUT_OF_STOCK_COUNT,
    (SELECT COUNT(*) FROM dbo.ITEM_MST WHERE ISNULL(QOH,0)<=ISNULL(REORDER_LVL,0) AND ISNULL(REORDER_LVL,0)>0 AND ISNULL(Discontinue,0)=0) AS REORDER_COUNT,
    (SELECT ISNULL(SUM(ISNULL(QOH,0)*ISNULL(CP,0)),0) FROM dbo.ITEM_MST WHERE ISNULL(Discontinue,0)=0) AS TOTAL_STOCK_VALUE,
    -- Customers
    (SELECT COUNT(*) FROM dbo.CUSTOMER_MST) AS TOTAL_CUSTOMERS,
    -- Purchases this month
    (SELECT ISNULL(SUM(GRANDTOTAL),0) FROM dbo.GRN_HDR WHERE YEAR(GRN_DATE)=YEAR(GETDATE()) AND MONTH(GRN_DATE)=MONTH(GETDATE()) AND ISNULL(ISCANCELLED,0)=0) AS MTD_PURCHASE
GO

PRINT '== PHASE 3 COMPLETE: 8 Analytics Views Created =='
GO

-- ================================================================
-- INDEXING FOR PERFORMANCE
-- ================================================================
PRINT '== CREATING INDEXES FOR PERFORMANCE =='
GO

IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name='IX_SALES_HDR_BILLDATE' AND object_id=OBJECT_ID('SALES_HDR'))
    CREATE NONCLUSTERED INDEX IX_SALES_HDR_BILLDATE ON dbo.SALES_HDR(BILL_DATE,ISCANCELLED) INCLUDE(GRAND_TOTAL,DISC_AMOUNT,CUSTOMER_CODE,SH_DEPT_CODE)
GO
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name='IX_SALES_DTL_BILLNO' AND object_id=OBJECT_ID('SALES_DTL'))
    CREATE NONCLUSTERED INDEX IX_SALES_DTL_BILLNO ON dbo.SALES_DTL(BILL_NO,SD_DEPT_CODE) INCLUDE(SERVICEORPRODUCTCODE,QTY,AMOUNT,ORG_CP,HSNSACCODE,TAX_AMOUNT)
GO
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name='IX_GRN_HDR_DATE' AND object_id=OBJECT_ID('GRN_HDR'))
    CREATE NONCLUSTERED INDEX IX_GRN_HDR_DATE ON dbo.GRN_HDR(GRN_DATE,ISCANCELLED) INCLUDE(SUPPLIERCODE,GRANDTOTAL,GH_DEPT_CODE)
GO
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name='IX_SALES_HDR_CUSTCODE' AND object_id=OBJECT_ID('SALES_HDR'))
    CREATE NONCLUSTERED INDEX IX_SALES_HDR_CUSTCODE ON dbo.SALES_HDR(CUSTOMER_CODE,BILL_DATE) WHERE CUSTOMER_CODE IS NOT NULL
GO

PRINT '== ALL DONE: 30 Views + Indexes Created Successfully! =='
GO
